import { QuizDefinition } from '../../../config/quiz/types';

/** Quizzes for the Lobby floor (ground floor). */
export const QUIZ_LOBBY: Record<string, QuizDefinition> = {
  /* --------------------------------------------------------- */
  /*  Architecture Elevator                                     */
  /* --------------------------------------------------------- */
  'architecture-elevator': {
    infoId: 'architecture-elevator',
    questions: [
      // ---- EASY ----
      {
        id: 'ae-e1',
        difficulty: 'easy',
        question: 'Who coined the term "Architecture Elevator"?',
        choices: ['Martin Fowler', 'Gregor Hohpe', 'Sam Newman', 'Kent Beck'],
        correctIndex: 1,
        explanation: 'Gregor Hohpe coined the term to describe how architects ride between business strategy and technical implementation.',
      },
      {
        id: 'ae-e2',
        difficulty: 'easy',
        question: 'What does the "penthouse" represent in the Architecture Elevator metaphor?',
        choices: [
          'The testing environment',
          'The production servers',
          'Business strategy and organizational decisions',
          'The development team\'s workspace',
        ],
        correctIndex: 2,
        explanation: 'The penthouse represents the strategic level where business decisions are made.',
      },
      {
        id: 'ae-e3',
        difficulty: 'easy',
        question: 'What does the "engine room" represent in the Architecture Elevator?',
        choices: [
          'The HR department',
          'Where technology is built and operated',
          'The project management office',
          'The executive boardroom',
        ],
        correctIndex: 1,
        explanation: 'The engine room is where the technology is built and operated — the hands-on technical level.',
      },
      // ---- MEDIUM ----
      {
        id: 'ae-m1',
        difficulty: 'medium',
        question: 'Why must an effective architect "ride the elevator" between floors?',
        choices: [
          'To get exercise during the workday',
          'To translate between business outcomes and technical systems',
          'To avoid being in too many meetings',
          'To monitor network infrastructure on each floor',
        ],
        correctIndex: 1,
        explanation: 'Architects translate between executives who speak in business outcomes and engineers who speak in systems and code.',
      },
      {
        id: 'ae-m2',
        difficulty: 'medium',
        question: 'What happens when an architect only stays in the "penthouse"?',
        choices: [
          'They become a more effective leader',
          'They gain better technical skills',
          'They become an "ivory tower" architect whose designs don\'t work in practice',
          'They save time by avoiding implementation details',
        ],
        correctIndex: 2,
        explanation: 'Architects who never leave the penthouse create impractical designs disconnected from operational reality.',
      },
      {
        id: 'ae-m3',
        difficulty: 'medium',
        question: 'What is the unique value that an architect creates according to the elevator metaphor?',
        choices: [
          'Writing the most code',
          'Connecting floors — ensuring strategy and implementation are aligned',
          'Managing the largest team',
          'Choosing the newest technologies',
        ],
        correctIndex: 1,
        explanation: 'The elevator ride itself — connecting strategy and implementation — is where architects create the most value.',
      },
      // ---- HARD ----
      {
        id: 'ae-h1',
        difficulty: 'hard',
        question: 'According to the deep dive, what does "riding up" the elevator specifically involve?',
        choices: [
          'Reporting status updates to management',
          'Translating technical constraints into business impact',
          'Escalating bugs to the operations team',
          'Requesting larger budgets for infrastructure',
        ],
        correctIndex: 1,
        explanation: 'Going up means translating technical constraints into business impact — making technology relevant to strategy.',
      },
      {
        id: 'ae-h2',
        difficulty: 'hard',
        question: 'What risk faces an architect who never leaves the "engine room"?',
        choices: [
          'They get promoted too quickly',
          'They become too popular with developers',
          'They miss the strategic context that should guide technical decisions',
          'They run out of technical challenges',
        ],
        correctIndex: 2,
        explanation: 'Staying only in the engine room means missing strategic context, leading to technically sound but strategically misaligned decisions.',
      },
      {
        id: 'ae-h3',
        difficulty: 'hard',
        question: 'The penthouse represents more than just the C-suite. What broader concept does it encompass?',
        choices: [
          'Only the CEO\'s office',
          'Strategic thinking about markets, competitive advantage, and organizational transformation',
          'The cloud infrastructure control panel',
          'The software testing pyramid',
        ],
        correctIndex: 1,
        explanation: 'The penthouse encompasses strategic thinking about markets, competitive advantage, and organizational transformation — not just executives.',
      },
      // ---- EASY (additional) ----
      {
        id: 'ae-e4',
        difficulty: 'easy',
        question: 'What language do executives typically speak, according to the Architecture Elevator?',
        choices: ['Assembly code', 'Business outcomes', 'Network protocols', 'Database queries'],
        correctIndex: 1,
        explanation: 'Executives speak in business outcomes; the architect\'s role is to translate between this language and the technical language of the engine room.',
      },
      {
        id: 'ae-e5',
        difficulty: 'easy',
        question: 'What language do engineers typically speak, according to the Architecture Elevator?',
        choices: ['ROI and market share', 'Budget projections', 'Systems and code', 'Legal compliance'],
        correctIndex: 2,
        explanation: 'Engineers speak in systems and code \u2014 the technical language that business executives do not usually share.',
      },
      {
        id: 'ae-e6',
        difficulty: 'easy',
        question: 'Which of these best describes the architect\'s role in the Architecture Elevator metaphor?',
        choices: [
          'A developer who writes the most code',
          'A translator between executives and engineers',
          'A project manager who tracks deadlines',
          'A system administrator who manages servers',
        ],
        correctIndex: 1,
        explanation: 'The architect rides the elevator specifically to translate between the business language of the penthouse and the technical language of the engine room.',
      },
      {
        id: 'ae-e7',
        difficulty: 'easy',
        question: 'On which website is the Architecture Elevator article by Gregor Hohpe published?',
        choices: ['aws.amazon.com', 'martinfowler.com', 'stackoverflow.com', 'infoq.com'],
        correctIndex: 1,
        explanation: 'Hohpe\'s Architecture Elevator article is published on martinfowler.com alongside his other architectural writing.',
      },
      {
        id: 'ae-e8',
        difficulty: 'easy',
        question: 'In the game inspired by the Architecture Elevator, what does the player literally do?',
        choices: [
          'Write code in the engine room',
          'Draw architecture diagrams',
          'Ride the elevator between floors representing different teams',
          'Attend executive board meetings',
        ],
        correctIndex: 2,
        explanation: 'The game has you literally ride the elevator between floors \u2014 each representing a different team \u2014 mirroring the architect\'s role of connecting levels.',
      },
      {
        id: 'ae-e9',
        difficulty: 'easy',
        question: 'What is Gregor Hohpe\'s book about the Architecture Elevator called?',
        choices: [
          '"Clean Architecture"',
          '"The Pragmatic Architect"',
          '"The Software Architect Elevator"',
          '"Architecture Patterns with Python"',
        ],
        correctIndex: 2,
        explanation: '"The Software Architect Elevator" is Hohpe\'s book exploring the architect\'s role in riding between strategy and implementation.',
      },
      {
        id: 'ae-e10',
        difficulty: 'easy',
        question: 'Business strategy and organizational decisions are made on which floor of the Architecture Elevator?',
        choices: ['The engine room', 'The basement', 'The penthouse', 'The mezzanine'],
        correctIndex: 2,
        explanation: 'The penthouse is where business strategy and organizational decisions are made \u2014 the strategic level of the organization.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'ae-m4',
        difficulty: 'medium',
        question: 'A CTO asks why a new platform costs 30% more. Which response best demonstrates "riding up" the elevator?',
        choices: [
          'Sending a detailed technical specification',
          'Deflecting to the engineering team for the answer',
          'Translating the cost into expected reduction in incident downtime and time-to-market impact',
          'Requesting more budget without context',
        ],
        correctIndex: 2,
        explanation: 'Riding up means converting technical choices into business impact \u2014 helping the CTO evaluate the investment in terms they can act on.',
      },
      {
        id: 'ae-m5',
        difficulty: 'medium',
        question: 'An architect answers a business question with a 10-minute Kubernetes deep-dive. What principle did they violate?',
        choices: [
          'They should have given a shorter Kubernetes explanation',
          'They failed to translate technical detail into business language for their audience',
          'They should have delegated to an engineer',
          'They spoke for too long in a meeting',
        ],
        correctIndex: 1,
        explanation: 'The elevator ride requires active translation \u2014 not reciting technical facts, but converting them into the language the listener uses.',
      },
      {
        id: 'ae-m6',
        difficulty: 'medium',
        question: 'When riding DOWN the elevator, what should an architect bring to the engine room?',
        choices: [
          'Budget spreadsheets from the finance team',
          'Business goals translated into technical direction',
          'A list of executive complaints about engineering',
          'Marketing collateral for new features',
        ],
        correctIndex: 1,
        explanation: 'Going down means taking business goals and converting them into concrete technical direction that guides engineering decisions.',
      },
      {
        id: 'ae-m7',
        difficulty: 'medium',
        question: 'Why can neither the penthouse nor the engine room function optimally without the elevator connection?',
        choices: [
          'Because they share the same physical infrastructure',
          'Strategy without implementation produces no results; implementation without strategy produces the wrong results',
          'Because the teams are on the same salary band',
          'Because both floors use the same monitoring tools',
        ],
        correctIndex: 1,
        explanation: 'Strategy and implementation are mutually dependent \u2014 architects create value by ensuring they remain aligned through continuous translation.',
      },
      {
        id: 'ae-m8',
        difficulty: 'medium',
        question: 'Which of these best describes an architect who NEVER rides down from the penthouse?',
        choices: [
          'A highly strategic thinker who creates long-term value',
          'An "ivory tower" architect whose designs don\'t work in practice',
          'A specialist who appropriately focuses on strategy',
          'An executive who also understands technology',
        ],
        correctIndex: 1,
        explanation: 'Staying only in the penthouse produces impractical designs disconnected from the operational reality of the engine room.',
      },
      {
        id: 'ae-m9',
        difficulty: 'medium',
        question: 'What does the Architecture Elevator say about architects who only work in the engine room?',
        choices: [
          'They produce the highest-quality code',
          'They miss the strategic context that should guide their technical decisions',
          'They are the most valuable type of architect',
          'They eventually develop business strategy skills naturally',
        ],
        correctIndex: 1,
        explanation: 'Engine-room-only architects are technically skilled but lack the strategic context needed to align their work with business goals.',
      },
      {
        id: 'ae-m10',
        difficulty: 'medium',
        question: 'What makes the architect\'s contribution unique compared to both executives and engineers?',
        choices: [
          'Architects hold more certifications than either group',
          'Architects write both business documents and code',
          'Architects actively translate between the strategic and technical worlds',
          'Architects manage larger teams than engineers',
        ],
        correctIndex: 2,
        explanation: 'The architect\'s unique value is the translation work \u2014 connecting two worlds that speak different languages about the same system.',
      },
      // ---- HARD (additional) ----
      {
        id: 'ae-h4',
        difficulty: 'hard',
        question: 'According to the deep dive, what does "riding down" the elevator specifically involve?',
        choices: [
          'Attending stand-up meetings with engineering',
          'Translating business goals into technical direction',
          'Writing deployment scripts',
          'Reporting sprint velocity to management',
        ],
        correctIndex: 1,
        explanation: 'The deep dive explicitly states: going down means translating business goals into technical direction \u2014 the complement of riding up.',
      },
      {
        id: 'ae-h5',
        difficulty: 'hard',
        question: 'According to the deep dive, the "engine room" goes beyond coding to encompass what?',
        choices: [
          'Marketing campaigns and customer feedback',
          'Legal compliance and contract review',
          'Operational reality, technical debt, and system constraints',
          'Finance and budget planning',
        ],
        correctIndex: 2,
        explanation: 'The engine room is the full operational reality: running systems, accumulating technical debt, and the constraints those systems impose on future decisions.',
      },
      {
        id: 'ae-h6',
        difficulty: 'hard',
        question: 'The deep dive describes the elevator ride as the moment when "the most value is created." What specifically happens in that moment?',
        choices: [
          'The architect writes detailed architecture documents',
          'Strategy and implementation become aligned \u2014 each floor\'s constraints and goals become legible to the other',
          'The architect attends every meeting on both floors',
          'New technology is evaluated and selected',
        ],
        correctIndex: 1,
        explanation: 'The deep dive states: "The act of connecting floors \u2014 of ensuring that strategy and implementation are aligned \u2014 is the architect\'s unique contribution."',
      },
      {
        id: 'ae-h7',
        difficulty: 'hard',
        question: 'A business goal is "reduce customer churn by 15%." An architect translates this into "all user-facing API responses must be under 200 ms." Which direction of the elevator is this?',
        choices: [
          'Riding up \u2014 turning technical constraints into business impact',
          'Neither \u2014 this is product management work',
          'Riding down \u2014 translating business goals into technical direction',
          'Staying in the engine room to investigate performance',
        ],
        correctIndex: 2,
        explanation: 'Business goal (reduce churn) \u2192 technical direction (response time target) is the downward ride \u2014 strategy descending into implementation guidance.',
      },
      {
        id: 'ae-h8',
        difficulty: 'hard',
        question: 'The deep dive says architects who stay only in the penthouse produce designs that "don\'t work in practice." What specific knowledge are they missing?',
        choices: [
          'The names of the engineering team members',
          'Operational reality, technical debt, and the true constraints the system operates under',
          'The programming languages currently in use',
          'The project timeline and milestones',
        ],
        correctIndex: 1,
        explanation: 'Without engine-room awareness, architects design for an idealized system rather than the real one \u2014 full of debt, constraints, and operational realities.',
      },
      {
        id: 'ae-h9',
        difficulty: 'hard',
        question: 'According to the deep dive, what does "actively translating context" mean when riding up?',
        choices: [
          'Simplifying technical terms for a non-technical audience',
          'Converting technical constraints into the business impact language executives use to make decisions',
          'Reporting status updates with less jargon',
          'Summarising engineering output for quarterly reviews',
        ],
        correctIndex: 1,
        explanation: 'Active translation means reframing technical constraints as business consequences \u2014 not just simplifying, but genuinely converting the currency of meaning.',
      },
      {
        id: 'ae-h10',
        difficulty: 'hard',
        question: 'The deep dive identifies a risk symmetric to the "ivory tower" architect. What is it?',
        choices: [
          'The architect who attends too many meetings',
          'The architect who stays only in the engine room and misses the strategic context guiding technical decisions',
          'The architect who produces too many diagrams',
          'The architect who manages too many teams simultaneously',
        ],
        correctIndex: 1,
        explanation: 'Both extremes are harmful: penthouse-only produces impractical designs; engine-room-only produces technically sound but strategically misaligned decisions.',
      },
    ],
  },
};
