import { QuizDefinition } from './types';

/** Quizzes for the Architecture Team floor (right room of floor 1). */
export const QUIZ_ARCHITECTURE: Record<string, QuizDefinition> = {
  /* --------------------------------------------------------- */
  /*  Architecture Team                                         */
  /* --------------------------------------------------------- */
  'architecture-team': {
    infoId: 'architecture-team',
    questions: [
      {
        id: 'at-e1',
        difficulty: 'easy',
        question: 'Which of these best describes what an architecture team primarily does?',
        choices: [
          'Writes the majority of the production code',
          'Helps other teams make better decisions',
          'Approves every pull request in the company',
          'Picks the programming language for every project',
        ],
        correctIndex: 1,
        explanation: 'A healthy architecture team amplifies other teams — guiding, connecting, and translating — rather than shipping the product themselves.',
      },
      {
        id: 'at-e2',
        difficulty: 'easy',
        question: 'According to Gregor Hohpe, architects should sell ___ instead of issuing mandates.',
        choices: ['orders', 'options', 'diagrams', 'roadmaps'],
        correctIndex: 1,
        explanation: 'Hohpe\'s phrase "sell options, don\'t issue mandates" captures the idea that architects preserve flexibility by deferring commitments until they\'re necessary.',
      },
      {
        id: 'at-e3',
        difficulty: 'easy',
        question: 'Which is NOT a typical role of the architecture team?',
        choices: [
          'Connector between teams working on overlapping problems',
          'Steward of cross-cutting concerns like security and reliability',
          'Single approver of every tech choice in the company',
          'Translator between business strategy and engineering',
        ],
        correctIndex: 2,
        explanation: 'Architects guide and connect; they do not centralise all decisions. Empowering teams to decide is the point.',
      },

      {
        id: 'at-m1',
        difficulty: 'medium',
        question: 'In Hohpe\'s framing, what is the "strike price" of an architectural option?',
        choices: [
          'The cost to start a new project',
          'The rework cost to change course later',
          'The licence fee of the chosen technology',
          'The time spent in design meetings',
        ],
        correctIndex: 1,
        explanation: 'The "strike price" is the cost of exercising the option — i.e. how expensive it is to switch later. Good architects keep it bounded.',
      },
      {
        id: 'at-m2',
        difficulty: 'medium',
        question: 'Why do mandates from an architecture team often fail in practice?',
        choices: [
          'Teams secretly dislike the architects',
          'Mandates commit the organisation before the commitment is needed, and are often ignored or worked around',
          'Mandates are always technically wrong',
          'Mandates violate open-source licences',
        ],
        correctIndex: 1,
        explanation: 'Premature commitment removes flexibility; teams routing around mandates is a symptom, not the cause.',
      },
      {
        id: 'at-m3',
        difficulty: 'medium',
        question: 'An architect notices two teams are independently building almost the same service. The best first action is to:',
        choices: [
          'Order one of the teams to stop immediately',
          'Connect the two teams and surface the overlap so they can decide together',
          'Build a third version themselves',
          'Ignore it — team autonomy is sacred',
        ],
        correctIndex: 1,
        explanation: 'Connecting teams is a core architecture-team function. Mandates would override autonomy; ignoring it wastes organisational effort.',
      },

      {
        id: 'at-h1',
        difficulty: 'hard',
        question: 'Which book by Gregor Hohpe popularised the "Architecture Elevator" metaphor?',
        choices: [
          '"Release It!"',
          '"The Software Architect Elevator"',
          '"Domain-Driven Design"',
          '"Accelerate"',
        ],
        correctIndex: 1,
        explanation: 'Hohpe\'s "The Software Architect Elevator" frames the architect\'s job as riding between penthouse (strategy) and engine room (technology).',
      },
      {
        id: 'at-h2',
        difficulty: 'hard',
        question: 'What does it mean for an architectural option to "expire"?',
        choices: [
          'The licence of a chosen technology runs out',
          'The moment the decision stops being cheap to defer — external pressure forces a commitment',
          'A new architect takes over and cancels it',
          'The option moves to a different team',
        ],
        correctIndex: 1,
        explanation: 'Options have an implicit expiry — scale, integration, or deadlines eventually force the decision to be taken. Good architects flag the expiry explicitly.',
      },
      {
        id: 'at-h3',
        difficulty: 'hard',
        question: 'Which statement best captures the architect\'s output in Hohpe\'s model?',
        choices: [
          'The number of architecture diagrams produced',
          'The quality of decisions made by the teams they support',
          'The count of mandates published per quarter',
          'Uptime of production systems',
        ],
        correctIndex: 1,
        explanation: 'Architects are leverage: their value shows up indirectly, in the decisions made by the teams around them.',
      },
      // ---- EASY (additional) ----
      {
        id: 'at-e4',
        difficulty: 'easy',
        question: 'What does "selling options" mean for an architect?',
        choices: [
          'Selling software licences to other teams',
          'Deferring irreversible commitments until needed, and making it cheap to change course later',
          'Providing multiple vendor quotes for a purchase',
          'Offering different pricing tiers for cloud services',
        ],
        correctIndex: 1,
        explanation: 'Selling options means keeping decisions flexible \u2014 naming the trigger that will force a commitment rather than deciding prematurely.',
      },
      {
        id: 'at-e5',
        difficulty: 'easy',
        question: 'Which cross-cutting concern is the architecture team typically the steward of?',
        choices: [
          'Individual developer performance reviews',
          'Sprint planning for each product team',
          'Security, reliability, and cost \u2014 concerns that span team boundaries',
          'Recruitment and hiring processes',
        ],
        correctIndex: 2,
        explanation: 'Cross-cutting concerns like security, reliability, and cost are not owned by any one product team \u2014 the architecture team stewards them across the organization.',
      },
      {
        id: 'at-e6',
        difficulty: 'easy',
        question: 'According to Gregor Hohpe, where does an architect\'s value actually show up?',
        choices: [
          'In the number of diagrams they produce',
          'In the quality of decisions made by the teams they support',
          'In the lines of code they contribute',
          'In the number of mandates they publish',
        ],
        correctIndex: 1,
        explanation: 'Architects work as leverage \u2014 their impact is indirect, appearing in the quality and speed of decisions made by the teams they guide and connect.',
      },
      {
        id: 'at-e7',
        difficulty: 'easy',
        question: 'What is the GUIDE role of the architecture team?',
        choices: [
          'Directing teams with binding technical decisions',
          'Helping teams see trade-offs and options they might otherwise miss',
          'Approving all technical choices before implementation',
          'Managing the backlog of all technical tasks',
        ],
        correctIndex: 1,
        explanation: 'The guide role is about expanding teams\' awareness of options and trade-offs \u2014 not directing, but illuminating so teams can decide well.',
      },
      {
        id: 'at-e8',
        difficulty: 'easy',
        question: 'What is the CONNECTOR role of the architecture team?',
        choices: [
          'Connecting cloud infrastructure components',
          'Linking teams working on overlapping problems so they can coordinate and learn from each other',
          'Connecting developers to job opportunities',
          'Connecting business to vendor contracts',
        ],
        correctIndex: 1,
        explanation: 'Connectors reduce duplicated effort and missed synergies by making sure teams with overlapping problems find each other.',
      },
      {
        id: 'at-e9',
        difficulty: 'easy',
        question: 'What does the architecture team\'s TRANSLATOR role involve?',
        choices: [
          'Translating technical documentation into other languages',
          'Bridging business strategy and engineering \u2014 converting between their different vocabularies',
          'Translating user requirements into wireframes',
          'Converting code from one programming language to another',
        ],
        correctIndex: 1,
        explanation: 'Translation is a core architect skill: business and engineering speak different languages; the architecture team makes each comprehensible to the other.',
      },
      {
        id: 'at-e10',
        difficulty: 'easy',
        question: 'Which of these is something a healthy architecture team does NOT do?',
        choices: [
          'Help teams understand trade-offs',
          'Connect teams with overlapping concerns',
          'Own all technology decisions centrally for the organization',
          'Bridge business strategy and engineering',
        ],
        correctIndex: 2,
        explanation: 'Centralizing all technology decisions defeats the purpose \u2014 it recreates the ivory tower. A healthy architecture team empowers teams to decide, not replaces their judgment.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'at-m4',
        difficulty: 'medium',
        question: 'An architect tells a team "you don\'t need to choose your message broker yet \u2014 but when you hit 10 k events/sec, that decision cannot wait." Which principle is this?',
        choices: [
          'Issuing a mandate about message broker selection',
          'Selling an option \u2014 naming the trigger that will force a commitment while deferring it until needed',
          'Suggesting the team should ignore the problem',
          'Over-engineering by planning for 10 k events/sec immediately',
        ],
        correctIndex: 1,
        explanation: 'Naming the trigger ("at 10 k events/sec") and the action ("you must decide") is how architects keep options alive without making premature commitments.',
      },
      {
        id: 'at-m5',
        difficulty: 'medium',
        question: 'Why do architecture team mandates "often get ignored or worked around," according to Hohpe?',
        choices: [
          'Teams are lazy or disrespectful of authority',
          'Mandates commit before the commitment is needed and remove flexibility, so teams route around them when they cause friction',
          'Mandates are always technically wrong',
          'Teams prefer to make decisions themselves for ego reasons',
        ],
        correctIndex: 1,
        explanation: 'When a mandate removes genuinely needed flexibility, teams find workarounds. The issue is premature commitment, not team culture.',
      },
      {
        id: 'at-m6',
        difficulty: 'medium',
        question: 'What does "the team writes the code; the architect keeps the option space alive" mean in practice?',
        choices: [
          'Architects refuse to take any implementation responsibility',
          'Architects focus on maintaining flexibility and pointing out consequences while teams make day-to-day implementation decisions',
          'Architects review all code before merge',
          'Teams don\'t need architects if they write good code',
        ],
        correctIndex: 1,
        explanation: 'Division of labour: teams deliver features; architects ensure the decisions those features depend on are made at the right time with full information.',
      },
      {
        id: 'at-m7',
        difficulty: 'medium',
        question: 'Two teams are independently building near-identical customer notification services. The architecture team\'s best first action is to:',
        choices: [
          'Order one team to stop building immediately',
          'Build a third shared notification service themselves',
          'Connect the two teams to surface the overlap and let them decide together how to align',
          'Ignore it \u2014 team autonomy is more important than efficiency',
        ],
        correctIndex: 2,
        explanation: 'The connector role surfaces overlaps. Letting teams see each other\'s work and decide for themselves preserves autonomy while eliminating blind duplication.',
      },
      {
        id: 'at-m8',
        difficulty: 'medium',
        question: 'In Hohpe\'s framing, what is the "expiry" of an architectural option?',
        choices: [
          'The moment the software license expires',
          'The moment the decision becomes too expensive to defer \u2014 scale, integrations, or deadlines force a commitment',
          'When the architect leaves the organization',
          'When a new technology makes the old choice obsolete automatically',
        ],
        correctIndex: 1,
        explanation: 'Options have an implicit expiry: conditions that make the decision unavoidable. Good architects name this trigger explicitly so teams aren\'t surprised.',
      },
      {
        id: 'at-m9',
        difficulty: 'medium',
        question: 'A team asks "which database should we use?" The architect responds by presenting three options with trade-offs and the conditions under which each is optimal. This is an example of:',
        choices: [
          'Passing the buck to the team',
          'Selling options \u2014 helping the team make a well-informed decision rather than imposing one choice',
          'Avoiding commitment irresponsibly',
          'Being indecisive under pressure',
        ],
        correctIndex: 1,
        explanation: 'Presenting options with trade-offs enables an informed decision by the team closest to the problem \u2014 rather than imposing a potentially premature commitment.',
      },
      {
        id: 'at-m10',
        difficulty: 'medium',
        question: 'What makes an architectural option different from simple indecision?',
        choices: [
          'They look identical from the outside',
          'An option is an explicit, named flexibility with a known trigger and bounded cost to exercise; indecision is an unmanaged unknown',
          'Options are written down; indecision isn\'t',
          'Options always involve financial instruments',
        ],
        correctIndex: 1,
        explanation: 'Managing options means explicitly tracking what can be deferred, when it must be decided, and what it will cost to change \u2014 indecision is the absence of that management.',
      },
      // ---- HARD (additional) ----
      {
        id: 'at-h4',
        difficulty: 'hard',
        question: 'In Hohpe\'s finance analogy, the "strike price" of an architectural option is the cost to:',
        choices: [
          'Buy a software licence',
          'Change course later \u2014 the rework cost if the deferred decision is eventually exercised',
          'Start a new project from scratch',
          'Hire an architect to make the decision',
        ],
        correctIndex: 1,
        explanation: 'The strike price is what you pay when you exercise the option: the rework cost of switching course. Good architects keep it bounded and known.',
      },
      {
        id: 'at-h5',
        difficulty: 'hard',
        question: 'Hohpe\'s deep dive says architects "work to keep options cheap to exercise." What does this mean concretely?',
        choices: [
          'Buy cheap software licences up front',
          'Design systems so that switching a key component later doesn\'t require a massive rewrite',
          'Avoid all irreversible decisions permanently',
          'Hire cheaper developers who are more flexible',
        ],
        correctIndex: 1,
        explanation: 'Keeping options cheap means reducing coupling and designing for replaceability \u2014 so when the trigger fires, exercising the option doesn\'t break everything.',
      },
      {
        id: 'at-h6',
        difficulty: 'hard',
        question: '"Architects collaborate with rather than command teams." According to the deep dive, why is this more effective?',
        choices: [
          'It avoids HR complaints about workplace culture',
          'Command-and-control architecture produces mandates teams route around; collaboration produces informed decisions teams own and execute',
          'Collaboration is always faster than issuing mandates',
          'Teams are always more technically competent than architects',
        ],
        correctIndex: 1,
        explanation: 'Mandates that bypass team buy-in get ignored or worked around. Options and informed guidance produce decisions teams own and execute well.',
      },
      {
        id: 'at-h7',
        difficulty: 'hard',
        question: 'Which paper, linked in the architecture-team info content, asks "Who Needs an Architect?"',
        choices: [
          'A paper by Kent Beck',
          'A paper by Martin Fowler',
          'A paper by Gregor Hohpe',
          'A paper by Sam Newman',
        ],
        correctIndex: 1,
        explanation: 'Martin Fowler\'s "Who Needs an Architect?" challenges and reframes what architects actually do in modern software development.',
      },
      {
        id: 'at-h8',
        difficulty: 'hard',
        question: 'According to Hohpe\'s options framing, why is it valuable to explicitly name the trigger that forces a decision?',
        choices: [
          'It gives architects credit for predicting the future',
          'It prevents teams from deciding too early (before needed) or too late (surprise rework cost)',
          'It satisfies audit requirements',
          'It allows decisions to be automated',
        ],
        correctIndex: 1,
        explanation: 'Naming the trigger prevents both under- and over-committing. Teams know exactly when they must decide, so they can prepare without premature optimization.',
      },
      {
        id: 'at-h9',
        difficulty: 'hard',
        question: 'An option has a "strike price" of six months of rework. The trigger is "when we integrate with System X." What should the architect do?',
        choices: [
          'Make the integration decision now to avoid the rework cost',
          'Defer the decision until integration with System X becomes a real requirement, then decide with full information',
          'Avoid integrating with System X entirely to preserve the option indefinitely',
          'Delegate the decision to the team with no further tracking',
        ],
        correctIndex: 1,
        explanation: 'Defer until the trigger fires. Deciding before the trigger wastes optionality; ignoring the trigger risks a surprise commitment cost when it arrives.',
      },
      {
        id: 'at-h10',
        difficulty: 'hard',
        question: 'The deep dive says the architect\'s job is to ensure "the cost of changing course later is bounded." What happens when this is neglected?',
        choices: [
          'Architecture diagrams become outdated',
          'Decisions are made with hidden costs \u2014 the rework price of reversing them is unknown and potentially enormous',
          'Teams gain too much flexibility',
          'Architects lose influence over time',
        ],
        correctIndex: 1,
        explanation: 'Unbounded rework cost is the architectural equivalent of unmanaged debt: invisible until it must be paid, and potentially existential when it arrives.',
      },
    ],
  },

  /* --------------------------------------------------------- */
  /*  C4 Model                                                  */
  /* --------------------------------------------------------- */
  'c4-diagrams': {
    infoId: 'c4-diagrams',
    questions: [
      {
        id: 'c4-e1',
        difficulty: 'easy',
        question: 'Who created the C4 model?',
        choices: ['Martin Fowler', 'Simon Brown', 'Eric Evans', 'Gregor Hohpe'],
        correctIndex: 1,
        explanation: 'Simon Brown created C4 as a lightweight way to describe software architecture at different levels of abstraction.',
      },
      {
        id: 'c4-e2',
        difficulty: 'easy',
        question: 'What are the four levels of the C4 model, from highest to lowest?',
        choices: [
          'Class, Container, Component, Context',
          'Context, Container, Component, Code',
          'Code, Component, Container, Context',
          'System, Service, Module, Method',
        ],
        correctIndex: 1,
        explanation: 'Context → Containers → Components → Code. Each step zooms in one level.',
      },
      {
        id: 'c4-e3',
        difficulty: 'easy',
        question: 'In C4, a "container" is best described as:',
        choices: [
          'A Docker container, specifically',
          'A deployable or executable unit (app, service, database)',
          'A UML package',
          'A folder on disk',
        ],
        correctIndex: 1,
        explanation: 'A C4 container is simply "a thing that runs" — a web app, a SPA, a job, or a database are all containers. Not specifically Docker.',
      },

      {
        id: 'c4-m1',
        difficulty: 'medium',
        question: 'Most teams using C4 day-to-day rely on which diagrams most often?',
        choices: [
          'Only the Code level',
          'The Context and Container diagrams',
          'All four levels equally',
          'Component and Code only',
        ],
        correctIndex: 1,
        explanation: 'Context and Container diagrams answer most conversations. Component is occasional; Code is usually skipped.',
      },
      {
        id: 'c4-m2',
        difficulty: 'medium',
        question: 'Which statement is TRUE about C4 notation?',
        choices: [
          'C4 is a strict UML profile',
          'C4 favours plain readability over formal notation; a legend explains colours and shapes',
          'C4 requires at least ten shape types per diagram',
          'C4 diagrams must be drawn in Visio',
        ],
        correctIndex: 1,
        explanation: 'C4 is deliberately NOT UML — it trades formality for readability. A simple legend is enough.',
      },
      {
        id: 'c4-m3',
        difficulty: 'medium',
        question: 'What problem do "diagrams as code" tools like Structurizr solve for C4 adoption?',
        choices: [
          'They replace the need for any diagrams at all',
          'They keep diagrams version-controlled and regenerable from a single source, so they don\'t silently rot',
          'They make diagrams harder to share',
          'They remove the need for a legend',
        ],
        correctIndex: 1,
        explanation: 'Diagrams-as-code puts the diagram in the repo, tied to the code, so it stays current instead of going stale in a wiki.',
      },

      {
        id: 'c4-h1',
        difficulty: 'hard',
        question: 'A common C4 mistake is to assume a container is:',
        choices: [
          'Always a microservice',
          'The same as a UML class',
          'A single source file',
          'An AWS EC2 instance',
        ],
        correctIndex: 0,
        explanation: 'Beginners often equate "container" with "microservice". A container is any deployable unit — mobile apps, SPAs, databases, and batch jobs all qualify.',
      },
      {
        id: 'c4-h2',
        difficulty: 'hard',
        question: 'Which C4 level is most useful for explaining the system to a NON-technical stakeholder?',
        choices: ['Code', 'Component', 'Container', 'Context'],
        correctIndex: 3,
        explanation: 'Context treats the system as a black box surrounded by people and external systems — the clearest view for business stakeholders.',
      },
      {
        id: 'c4-h3',
        difficulty: 'hard',
        question: 'What is the main purpose of the "Code" level in C4, and why is it often skipped?',
        choices: [
          'To replace unit tests; it\'s skipped because tests suffice',
          'To show classes/interfaces inside a component; it\'s skipped because IDEs already generate this on demand',
          'To produce deployment diagrams; it\'s skipped because operations owns those',
          'To act as a legal record of the architecture',
        ],
        correctIndex: 1,
        explanation: 'Code-level diagrams duplicate what modern IDEs show at a click. C4 recommends skipping them unless genuinely helpful.',
      },
      // ---- EASY (additional) ----
      {
        id: 'c4-e4',
        difficulty: 'easy',
        question: 'What philosophy does Simon Brown use to describe the C4 model?',
        choices: [
          '"One diagram to rule them all"',
          '"A map of your code, at different zoom levels"',
          '"Always use formal UML notation"',
          '"Diagrams must be maintained by architects only"',
        ],
        correctIndex: 1,
        explanation: 'Brown describes C4 as "a map of your code, at different zoom levels" \u2014 emphasising that each level serves a different audience and conversation.',
      },
      {
        id: 'c4-e5',
        difficulty: 'easy',
        question: 'What does the C4 Context diagram show?',
        choices: [
          'The classes inside the application',
          'The system as a black box, plus the people and external systems it interacts with',
          'The deployment infrastructure in detail',
          'The release pipeline steps',
        ],
        correctIndex: 1,
        explanation: 'Context is the outermost view: your system as a black box, surrounded by the actors and external systems that interact with it.',
      },
      {
        id: 'c4-e6',
        difficulty: 'easy',
        question: 'In C4, what does a "Component" represent?',
        choices: [
          'A microservice',
          'A cloud region',
          'A building block inside a container \u2014 a module, package, or internal service',
          'A type of user',
        ],
        correctIndex: 2,
        explanation: 'Components live inside containers and are the logical building blocks: modules, packages, named services. They are NOT the same as microservices.',
      },
      {
        id: 'c4-e7',
        difficulty: 'easy',
        question: 'Who should be able to understand a C4 Context diagram without any prior technical training?',
        choices: [
          'Only software architects',
          'Only senior engineers',
          'Only DevOps engineers',
          'A new joiner or business stakeholder \u2014 it is designed for broad readability',
        ],
        correctIndex: 3,
        explanation: 'The Context diagram is the most accessible level: simple enough that any stakeholder can understand who uses the system and what it connects to.',
      },
      {
        id: 'c4-e8',
        difficulty: 'easy',
        question: 'Which C4 level is frequently skipped because modern IDEs generate the same information on demand?',
        choices: ['Context', 'Container', 'Component', 'Code'],
        correctIndex: 3,
        explanation: 'The Code level (classes, interfaces) is often skipped because IDEs show this automatically. Maintaining a separate Code-level diagram rarely adds value.',
      },
      {
        id: 'c4-e9',
        difficulty: 'easy',
        question: 'What do arrows in a C4 diagram represent?',
        choices: [
          'Only network traffic flows',
          'Dependency or calling relationships \u2014 "A depends on / calls B"',
          'Data volumes per second',
          'Security boundaries',
        ],
        correctIndex: 1,
        explanation: 'In C4, an arrow consistently means "depends on" or "calls." This consistent meaning is part of the notation\'s readability.',
      },
      {
        id: 'c4-e10',
        difficulty: 'easy',
        question: 'C4 diagrams are deliberately NOT which type of formal notation?',
        choices: ['Markdown', 'UML', 'JSON', 'YAML'],
        correctIndex: 1,
        explanation: 'C4 favours plain readability over formal UML notation. A simple legend replaces the need to learn a standard notation.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'c4-m4',
        difficulty: 'medium',
        question: 'A team needs to explain their system to a new CTO with no technical background. Which C4 level should they use first?',
        choices: ['Code', 'Component', 'Container', 'Context'],
        correctIndex: 3,
        explanation: 'Context is the most accessible: the system as a black box, surrounded by users and external systems. Perfect for business stakeholders.',
      },
      {
        id: 'c4-m5',
        difficulty: 'medium',
        question: 'A developer says "our C4 container diagram shows all 27 of our microservices." What is the likely problem?',
        choices: [
          'Nothing \u2014 containers ARE microservices in C4',
          '27 items on one diagram may defeat C4\'s readability goal; a C4 container is also not specifically a microservice',
          'Microservices should only appear in the Component diagram',
          'The diagram must be split by team ownership',
        ],
        correctIndex: 1,
        explanation: 'The confusion of "container = microservice" is common. More importantly, 27 items on one diagram often defeats C4\'s readability purpose.',
      },
      {
        id: 'c4-m6',
        difficulty: 'medium',
        question: 'What specific problem do "diagrams-as-code" tools like Structurizr solve for C4?',
        choices: [
          'They generate diagrams automatically from source code without any input',
          'They keep diagrams version-controlled and regenerable from a single source, preventing silent staleness',
          'They replace the need for architecture reviews',
          'They enforce UML compliance',
        ],
        correctIndex: 1,
        explanation: 'Diagrams-as-code in a repo ages with the code \u2014 when the architecture changes, the diagram can be regenerated. Diagrams in wikis drift silently.',
      },
      {
        id: 'c4-m7',
        difficulty: 'medium',
        question: 'A container diagram shows a web app, an API, a database, and a message queue. Which are correctly described as C4 "containers"?',
        choices: [
          'Only the web app',
          'Only the database',
          'Only the API',
          'All four \u2014 each is a deployable or executable unit',
        ],
        correctIndex: 3,
        explanation: 'A C4 container is anything that runs: a web app, an API server, a database, a message queue, or a batch job all qualify.',
      },
      {
        id: 'c4-m8',
        difficulty: 'medium',
        question: 'The C4 Component level zooms inside which element?',
        choices: [
          'A person or external system in the Context diagram',
          'A specific container',
          'The entire system context',
          'A code-level class',
        ],
        correctIndex: 1,
        explanation: 'Component diagrams live inside a single container, showing its internal building blocks. You choose one container to zoom into at a time.',
      },
      {
        id: 'c4-m9',
        difficulty: 'medium',
        question: 'Why does C4 advise to "be ruthless about what to leave out"?',
        choices: [
          'Diagrams must fit on a single A4 page by standard',
          'Clarity comes from omission; including every detail recreates the spider-web diagrams C4 was designed to replace',
          'There is a technical limit to C4 diagram size',
          'Leaving things out protects intellectual property',
        ],
        correctIndex: 1,
        explanation: 'The value of C4 diagrams is their focus. Every element added for completeness reduces the diagram\'s usefulness for the conversation it is designed to support.',
      },
      {
        id: 'c4-m10',
        difficulty: 'medium',
        question: 'Which C4 diagram would you choose to show which technology stack runs in each deployable unit?',
        choices: ['Context', 'Component', 'Container', 'Code'],
        correctIndex: 2,
        explanation: 'The Container diagram shows the deployable/executable units, their technologies, and how they communicate \u2014 the right level for deployment and technology questions.',
      },
      // ---- HARD (additional) ----
      {
        id: 'c4-h4',
        difficulty: 'hard',
        question: 'The deep dive says most architecture diagrams "fail because they try to say everything on one page." What is the specific consequence?',
        choices: [
          'Legal liability for incorrect information',
          'A spider web of boxes nobody can read that goes stale the day it is drawn',
          'Too much information for the build system to parse',
          'Expensive licensing costs for diagram tools',
        ],
        correctIndex: 1,
        explanation: 'The "say everything" impulse produces diagrams that are unreadable and unmaintainable. C4\'s hierarchy solves this by giving each zoom level ONE job.',
      },
      {
        id: 'c4-h5',
        difficulty: 'hard',
        question: 'According to the deep dive, which three explicit choices make C4 succeed?',
        choices: [
          'Colour coding, icon libraries, and layered templates',
          'Hierarchical abstraction, notation consistency, and living artefacts',
          'XML schema, version numbers, and access controls',
          'Simplicity, brevity, and formal review processes',
        ],
        correctIndex: 1,
        explanation: 'The deep dive names three design decisions: hierarchical abstraction (each diagram has one job), notation consistency (terms mean one thing), and living artifacts (diagrams-as-code).',
      },
      {
        id: 'c4-h6',
        difficulty: 'hard',
        question: 'According to the deep dive, what is the key consequence of "notation consistency"?',
        choices: [
          'Every diagram looks visually identical',
          'A reader learns the notation once and applies it everywhere \u2014 reducing the cognitive overhead of reading any C4 diagram',
          'All diagrams must be drawn by the same person',
          'Consistency is enforced by a linting tool',
        ],
        correctIndex: 1,
        explanation: 'Consistent notation means "container" always means one thing and arrows always mean one thing. Once learned, the notation is universal across all C4 diagrams.',
      },
      {
        id: 'c4-h7',
        difficulty: 'hard',
        question: 'A common C4 mistake is assuming "Container" and "Microservice" are synonyms. Why is this wrong?',
        choices: [
          'Microservices don\'t run in containers',
          'A container is any deployable unit \u2014 a mobile app, SPA, batch job, or database are all containers but not necessarily microservices',
          'Microservices are shown at the Component level',
          'Containers are only databases and message queues',
        ],
        correctIndex: 1,
        explanation: 'The term "container" is independent of microservices. It means "a thing that runs" \u2014 which includes apps, services, jobs, databases, and message buses.',
      },
      {
        id: 'c4-h8',
        difficulty: 'hard',
        question: 'The deep dive states that "service boundaries show up at the COMPONENT level, if at all." What does this imply about the Container level?',
        choices: [
          'Container diagrams must show service boundaries explicitly',
          'Container diagrams show deployable units and communication, not internal service boundary decisions',
          'Service boundaries don\'t exist in C4 at any level',
          'Component diagrams are only relevant for microservices',
        ],
        correctIndex: 1,
        explanation: 'Container diagrams show "what runs and how they communicate." The decomposition into service boundaries is a Component-level concern, if it needs to be shown at all.',
      },
      {
        id: 'c4-h9',
        difficulty: 'hard',
        question: 'What does "living artefact" mean for a C4 diagram maintained with Structurizr or PlantUML C4 extension?',
        choices: [
          'The diagram updates automatically on every code deploy',
          'The diagram is in source control, regenerable from the same model, so it can be updated when the architecture changes',
          'The diagram has an expiry date and must be redrawn annually',
          'The diagram is connected to a live production database',
        ],
        correctIndex: 1,
        explanation: 'Diagrams-as-code means the diagram lives in the repo, is regenerable, and can be reviewed and updated in the same workflow as the code it describes.',
      },
      {
        id: 'c4-h10',
        difficulty: 'hard',
        question: 'A practical implication of "service boundaries show up at the COMPONENT level, if at all" is that Container diagrams should:',
        choices: [
          'List every microservice for completeness and accuracy',
          'Focus on deployable units and their communication, not on internal decomposition decisions',
          'Always be more important than Component diagrams',
          'Show service boundaries as separate nested boxes',
        ],
        correctIndex: 1,
        explanation: 'Container diagrams are for deployment topology and technology choices. Showing internal service decomposition at this level adds noise rather than clarity.',
      },
    ],
  },

  /* --------------------------------------------------------- */
  /*  Vertical Slice Architecture                               */
  /* --------------------------------------------------------- */
  'vertical-slice-architecture': {
    infoId: 'vertical-slice-architecture',
    questions: [
      {
        id: 'vsa-e1',
        difficulty: 'easy',
        question: 'Vertical Slice Architecture organises code primarily by:',
        choices: ['Technical layer', 'Feature', 'Team', 'Programming language'],
        correctIndex: 1,
        explanation: 'Each slice contains everything one feature needs — HTTP, validation, business logic, persistence — in one place.',
      },
      {
        id: 'vsa-e2',
        difficulty: 'easy',
        question: 'Who popularised Vertical Slice Architecture?',
        choices: ['Eric Evans', 'Jimmy Bogard', 'Kent Beck', 'Uncle Bob'],
        correctIndex: 1,
        explanation: 'Jimmy Bogard (author of MediatR and AutoMapper) wrote the seminal posts on vertical slices.',
      },
      {
        id: 'vsa-e3',
        difficulty: 'easy',
        question: 'In a traditional n-layer architecture, changing one feature typically means editing:',
        choices: [
          'A single file',
          'One folder',
          'Multiple files across multiple layer folders (Controllers, Services, Repositories, etc.)',
          'Only the database',
        ],
        correctIndex: 2,
        explanation: 'Horizontal layering spreads one feature across every layer — vertical slices collapse that into a single folder.',
      },

      {
        id: 'vsa-m1',
        difficulty: 'medium',
        question: 'Which of these is a real trade-off of Vertical Slice Architecture?',
        choices: [
          'It cannot be tested',
          'Some code that would be shared in an n-layer design ends up duplicated across slices',
          'It only works in Java',
          'It removes the need for a database',
        ],
        correctIndex: 1,
        explanation: 'Vertical slices intentionally accept some duplication to avoid the wrong shared abstraction. "A little duplication is cheaper than the wrong coupling."',
      },
      {
        id: 'vsa-m2',
        difficulty: 'medium',
        question: 'Vertical slices pair naturally with which pattern?',
        choices: [
          'Singleton everywhere',
          'CQRS — separate Command and Query handlers',
          'Global mutable state',
          'Inheritance over composition',
        ],
        correctIndex: 1,
        explanation: 'Each slice is typically one command or one query handler — a CQRS-shaped unit of behaviour.',
      },
      {
        id: 'vsa-m3',
        difficulty: 'medium',
        question: 'In vertical-slice parlance, what is meant by "tailored design per slice"?',
        choices: [
          'Each slice must use a different framework',
          'Simple features stay simple; complex ones can add layers only where those layers genuinely help',
          'Each slice needs its own database',
          'Only senior developers can design a slice',
        ],
        correctIndex: 1,
        explanation: 'Vertical slices free you from forcing every feature through the same layered template. Design complexity goes where it earns its keep.',
      },

      {
        id: 'vsa-h1',
        difficulty: 'hard',
        question: 'Why is CreateInvoice able to use a totally different design (e.g. event-sourced) from VoidInvoice in a vertical-slice codebase?',
        choices: [
          'Because the compiler enforces it',
          'Because the two slices are independent — they do not share a central Service<Invoice> that couples them',
          'Because Jimmy Bogard requires it',
          'Because they use different programming languages',
        ],
        correctIndex: 1,
        explanation: 'Independence is the point: each slice is free to pick the design best suited to its feature, since slices don\'t funnel through a shared service layer.',
      },
      {
        id: 'vsa-h2',
        difficulty: 'hard',
        question: 'Vertical Slice Architecture echoes which idea from Uncle Bob?',
        choices: [
          'The Repository Pattern',
          'Screaming Architecture — the folder structure should scream what the system DOES, not what framework it uses',
          'Dependency Injection as a religion',
          'The Open/Closed Principle',
        ],
        correctIndex: 1,
        explanation: 'Screaming Architecture: a new joiner reading the top-level folders should see "CreateInvoice, SendReceipt, RefundOrder" — the business — not "Controllers, Services, Repos".',
      },
      {
        id: 'vsa-h3',
        difficulty: 'hard',
        question: 'What is the relationship between vertical slices and MediatR-style "request/handler" libraries?',
        choices: [
          'MediatR is required by the vertical-slice pattern',
          'MediatR (or equivalents) provide a clean way to pipe one request to one handler, matching the one-slice-one-feature shape',
          'Vertical slices are only legal in C#',
          'MediatR forces horizontal layering',
        ],
        correctIndex: 1,
        explanation: 'MediatR\'s request→handler mapping naturally expresses "one feature, one handler", making vertical slices easy to implement.',
      },
      // ---- EASY (additional) ----
      {
        id: 'vsa-e4',
        difficulty: 'easy',
        question: 'In a vertical-slice codebase, what does the folder name "CreateOrder/" immediately tell a developer?',
        choices: [
          'Which programming language is used',
          'Which team owns the code',
          'What business capability the feature implements',
          'Which database table is involved',
        ],
        correctIndex: 2,
        explanation: 'In vertical slices, folder names reflect business capabilities. "CreateOrder/" tells you what the feature does before you open a single file.',
      },
      {
        id: 'vsa-e5',
        difficulty: 'easy',
        question: 'What does the term "slice" refer to in Vertical Slice Architecture?',
        choices: [
          'A network partition',
          'A feature containing all the code it needs \u2014 from HTTP handler to database access',
          'A horizontal layer of the application',
          'A team boundary',
        ],
        correctIndex: 1,
        explanation: 'A slice is a self-contained unit for one feature: it owns everything from the HTTP handler through validation, business logic, and persistence.',
      },
      {
        id: 'vsa-e6',
        difficulty: 'easy',
        question: 'What makes it easier to DELETE a feature in a vertical-slice codebase?',
        choices: [
          'Because slices are always small in size',
          'Because each feature is isolated in one folder with high cohesion and low coupling to unrelated features',
          'Because there is no database involved',
          'Because features are deployed as separate services',
        ],
        correctIndex: 1,
        explanation: 'High cohesion and low coupling per slice means deleting a feature is as simple as removing its folder \u2014 nothing in other slices depends on it.',
      },
      {
        id: 'vsa-e7',
        difficulty: 'easy',
        question: 'What does "low coupling" mean in the context of vertical slices?',
        choices: [
          'Slices share absolutely no code with each other',
          'Unrelated features cannot accidentally share state or constrain each other\'s design',
          'Each slice has its own dedicated server',
          'Slices only communicate via a REST API',
        ],
        correctIndex: 1,
        explanation: 'Low coupling means unrelated features are independent \u2014 changes in one slice cannot accidentally break another.',
      },
      {
        id: 'vsa-e8',
        difficulty: 'easy',
        question: 'Which library does Jimmy Bogard maintain that enables the request/handler pattern commonly used in vertical slices?',
        choices: ['Entity Framework', 'AutoMapper only', 'MediatR', 'ASP.NET Core'],
        correctIndex: 2,
        explanation: 'MediatR provides the request→handler pipeline that makes it easy to implement one-slice-one-handler in C# projects.',
      },
      {
        id: 'vsa-e9',
        difficulty: 'easy',
        question: 'What is "high cohesion" in the context of a vertical slice?',
        choices: [
          'Everything about one feature is co-located in one place',
          'All database code lives in one central folder',
          'All HTTP handlers live in one central folder',
          'All validators are grouped together',
        ],
        correctIndex: 0,
        explanation: 'High cohesion means everything that belongs to one feature lives together \u2014 the command, handler, validator, and query are all in the same slice.',
      },
      {
        id: 'vsa-e10',
        difficulty: 'easy',
        question: 'Vertical Slice Architecture is most directly an alternative to which traditional approach?',
        choices: [
          'Domain-Driven Design',
          'Microservices',
          'Horizontal n-layer architecture (Controllers, Services, Repositories)',
          'Event-driven architecture',
        ],
        correctIndex: 2,
        explanation: 'Vertical slices invert the n-layer split: instead of organising by technical layer, you organise by feature/business capability.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'vsa-m4',
        difficulty: 'medium',
        question: 'A team is adding a feature to a vertical-slice codebase. Which files are most likely to change?',
        choices: [
          'Controllers.cs, Services.cs, and Repositories.cs across multiple folders',
          'Only the files within the single feature\'s slice folder',
          'The shared BaseController and the ServiceRegistry',
          'The entire persistence layer',
        ],
        correctIndex: 1,
        explanation: 'In vertical slices, a feature change touches only its own slice. No other folders need to open.',
      },
      {
        id: 'vsa-m5',
        difficulty: 'medium',
        question: 'In a vertical-slice system, where does shared infrastructure like authentication or logging go?',
        choices: [
          'It is duplicated in every slice',
          'It lives in small explicit "shared" modules that slices consciously consume',
          'It doesn\'t exist \u2014 each slice handles it independently',
          'It goes in a giant horizontal layer at the top of the codebase',
        ],
        correctIndex: 1,
        explanation: 'Shared infrastructure exists but is minimal and explicit \u2014 small "shared" modules that slices reference intentionally, not giant layers every slice inherits from.',
      },
      {
        id: 'vsa-m6',
        difficulty: 'medium',
        question: 'What does Jimmy Bogard mean by "the wrong abstraction"?',
        choices: [
          'An abstraction that is too large for its purpose',
          'A shared layer that forces unrelated features to conform to one design, creating accidental coupling',
          'An abstraction written in the wrong programming language',
          'An abstraction that is insufficiently documented',
        ],
        correctIndex: 1,
        explanation: 'The wrong abstraction is one where unrelated features must share a design just to fit through a central layer \u2014 coupling them in ways that hurt both.',
      },
      {
        id: 'vsa-m7',
        difficulty: 'medium',
        question: 'How does a vertical-slice codebase "scream what the system does," in Uncle Bob\'s phrase?',
        choices: [
          'The code comments describe every business rule',
          'The top-level folder structure reflects business capabilities rather than framework layers',
          'The README lists all features explicitly',
          'Class names use business terminology throughout',
        ],
        correctIndex: 1,
        explanation: 'A new joiner reading "CreateOrder/, CancelOrder/, ShipOrder/" immediately understands the system\'s purpose \u2014 not its technical stack.',
      },
      {
        id: 'vsa-m8',
        difficulty: 'medium',
        question: 'What problem does a typical n-layer Service<Invoice> class create as the system grows?',
        choices: [
          'It is too slow at runtime',
          'It grows to handle ALL invoice scenarios, coupling unrelated features through one central class',
          'It uses too much memory',
          'It violates the Open/Closed Principle by definition',
        ],
        correctIndex: 1,
        explanation: 'A central Service<Invoice> accumulates every invoice operation, making unrelated features depend on each other\'s constraints and side-effects.',
      },
      {
        id: 'vsa-m9',
        difficulty: 'medium',
        question: 'Why does vertical-slice architecture consider some duplication acceptable?',
        choices: [
          'Because storage is cheap in modern cloud environments',
          'Because a little duplication is less harmful than coupling features through the wrong shared abstraction',
          'Because teams prefer simpler code overall',
          'Because duplicated code is easier to test in isolation',
        ],
        correctIndex: 1,
        explanation: 'Forced sharing through an imperfect abstraction creates coupling that\'s harder to remove than duplicated code. VSA accepts the trade-off deliberately.',
      },
      {
        id: 'vsa-m10',
        difficulty: 'medium',
        question: 'A new developer joins and sees top-level folders named "CreateOrder/", "CancelOrder/", "ShipOrder/". What do they immediately know?',
        choices: [
          'The technical stack the system uses',
          'The business operations the system supports \u2014 they understand what the system does before reading any code',
          'The database schema structure',
          'The team\'s sprint history',
        ],
        correctIndex: 1,
        explanation: 'Feature-named folders communicate the system\'s purpose instantly \u2014 the "screaming architecture" benefit of vertical slices.',
      },
      // ---- HARD (additional) ----
      {
        id: 'vsa-h4',
        difficulty: 'hard',
        question: 'The deep dive says horizontal layering "optimises for the wrong thing." What does it actually optimise for?',
        choices: [
          'Developer experience during feature work',
          'Ease of drawing architecture diagrams',
          'Runtime performance',
          'Testing isolation',
        ],
        correctIndex: 1,
        explanation: 'Horizontal layers look tidy on a diagram but optimise for that visual cleanliness, not for the actual axis of change: features.',
      },
      {
        id: 'vsa-h5',
        difficulty: 'hard',
        question: 'Why can CreateInvoice use pure CRUD while VoidInvoice uses event-sourcing in a vertical-slice codebase?',
        choices: [
          'Because they use different frameworks',
          'Because they are independent slices with no shared service layer constraining their design',
          'Because CRUD and event-sourcing use different databases',
          'Because the compiler enforces different patterns per folder',
        ],
        correctIndex: 1,
        explanation: 'Independence is the point: each slice is free to pick the design best suited to its feature, since slices don\'t funnel through a shared service layer.',
      },
      {
        id: 'vsa-h6',
        difficulty: 'hard',
        question: 'According to the deep dive, what is the "axis of change" that vertical slices optimise for?',
        choices: [
          'Changes to the technical stack',
          'Feature changes \u2014 the unit of work is a feature, so the unit of code is also a feature',
          'Database schema changes',
          'Infrastructure changes',
        ],
        correctIndex: 1,
        explanation: 'Vertical slices align the code structure with the most common kind of change: adding, modifying, or removing a feature.',
      },
      {
        id: 'vsa-h7',
        difficulty: 'hard',
        question: 'What is the relationship between "Screaming Architecture" (Uncle Bob) and Vertical Slice Architecture?',
        choices: [
          'They are unrelated concepts from different eras',
          'Screaming Architecture says structure should reveal intent; VSA implements this by making top-level folders reflect business capabilities',
          'Screaming Architecture requires vertical slices by definition',
          'Uncle Bob invented vertical slices',
        ],
        correctIndex: 1,
        explanation: 'VSA is one concrete realisation of Screaming Architecture: a new joiner reads the folders and sees the business domain, not the framework.',
      },
      {
        id: 'vsa-h8',
        difficulty: 'hard',
        question: 'According to the deep dive, CQRS pairs well with VSA because:',
        choices: [
          'CQRS requires microservices, and VSA requires microservices',
          'Each slice is typically one command or one query handler \u2014 a natural one-to-one mapping',
          'CQRS mandates vertical slices in its specification',
          'CQRS solves the duplication problem that VSA introduces',
        ],
        correctIndex: 1,
        explanation: 'CQRS\'s request→handler shape maps directly to the one-slice-one-feature structure, making the two patterns highly complementary.',
      },
      {
        id: 'vsa-h9',
        difficulty: 'hard',
        question: 'Why does Jimmy Bogard argue that "a little duplication beats the wrong abstraction"?',
        choices: [
          'Duplication is always cheaper than abstraction',
          'Forced sharing through an imperfect abstraction creates coupling that is harder to remove than duplicated code',
          'Duplication is easier to test in isolation',
          'The wrong abstraction can always be refactored easily later',
        ],
        correctIndex: 1,
        explanation: 'The cost of the wrong abstraction compounds over time as more features adapt to fit through it. Localised duplication stays localised and can be removed cleanly.',
      },
      {
        id: 'vsa-h10',
        difficulty: 'hard',
        question: 'In the deep dive, what does "shared infrastructure" look like in a well-designed vertical-slice system?',
        choices: [
          'Placed in giant horizontal layers above each slice',
          'Small, explicit "shared" modules that slices actively and consciously consume',
          'Merged directly into every slice via copy-paste',
          'It does not exist at all in a pure vertical-slice system',
        ],
        correctIndex: 1,
        explanation: 'Shared modules exist but are small and explicit \u2014 not the dominant structure of the codebase. Slices reference them intentionally, not by default.',
      },
    ],
  },

  /* --------------------------------------------------------- */
  /*  Architecture Decision Records                             */
  /* --------------------------------------------------------- */
  'architecture-decision-records': {
    infoId: 'architecture-decision-records',
    questions: [
      // ---- EASY ----
      {
        id: 'adr-e1',
        difficulty: 'easy',
        question: 'What does ADR stand for?',
        choices: [
          'Application Deployment Record',
          'Architecture Decision Record',
          'Automated Data Recovery',
          'Agile Delivery Roadmap',
        ],
        correctIndex: 1,
        explanation: 'ADR stands for Architecture Decision Record — a short, numbered document capturing one significant architectural decision.',
      },
      {
        id: 'adr-e2',
        difficulty: 'easy',
        question: 'Where do ADRs typically live?',
        choices: [
          'Only in a shared confluence space nobody reads',
          'In the repository alongside the code (e.g. docs/adr/)',
          'In the architect\'s private notebook',
          'On the company wiki, separate from the code',
        ],
        correctIndex: 1,
        explanation: 'ADRs live next to the code they describe — usually in a docs/adr/ folder — so they\'re version-controlled and reviewed with the same workflow as the code.',
      },
      {
        id: 'adr-e3',
        difficulty: 'easy',
        question: 'Which section of a typical ADR captures "what becomes easier, harder, or riskier" after the decision?',
        choices: [
          'Status',
          'Context',
          'Decision',
          'Consequences',
        ],
        correctIndex: 3,
        explanation: 'The Consequences section is where trade-offs are made explicit — arguably the most valuable part of an ADR for future readers.',
      },

      // ---- MEDIUM ----
      {
        id: 'adr-m1',
        difficulty: 'medium',
        question: 'What should you do when an accepted ADR no longer reflects the chosen architecture?',
        choices: [
          'Edit the original ADR to reflect the new decision',
          'Delete the ADR so it does not confuse readers',
          'Write a new ADR that supersedes it; mark the old one superseded',
          'Move the ADR to an archive folder and start over',
        ],
        correctIndex: 2,
        explanation: 'ADRs are immutable. You write a new ADR that supersedes the old one, preserving the history of why the earlier decision was made.',
      },
      {
        id: 'adr-m2',
        difficulty: 'medium',
        question: 'Which of these is the best scope for a single ADR?',
        choices: [
          'One ADR covering all persistence, messaging, and auth decisions',
          'One ADR per major quarter of work',
          'One ADR per architectural decision',
          'One ADR per microservice',
        ],
        correctIndex: 2,
        explanation: 'Granularity matters: one ADR = one decision. Small, focused ADRs are easier to read, supersede, and search later.',
      },
      {
        id: 'adr-m3',
        difficulty: 'medium',
        question: 'Why are ADRs usually append-only and never edited after acceptance?',
        choices: [
          'File systems make editing hard',
          'To preserve the history of thinking so future teams can understand why decisions were made',
          'Because tooling requires it',
          'To discourage people from ever revisiting decisions',
        ],
        correctIndex: 1,
        explanation: 'Immutability preserves the record of *why* a decision was made at a point in time — critical context when the world changes and a new ADR supersedes it.',
      },

      // ---- HARD ----
      {
        id: 'adr-h1',
        difficulty: 'hard',
        question: 'Who is generally credited with popularizing the lightweight ADR format?',
        choices: [
          'Martin Fowler',
          'Michael Nygard',
          'Gregor Hohpe',
          'Robert C. Martin',
        ],
        correctIndex: 1,
        explanation: 'Michael Nygard proposed lightweight ADRs in his 2011 post "Documenting Architecture Decisions" as an alternative to heavyweight architecture docs.',
      },
      {
        id: 'adr-h2',
        difficulty: 'hard',
        question: 'Which statement best captures why ADRs pair naturally with "You build it, you run it"?',
        choices: [
          'Running systems require fewer decisions than building them',
          'ADRs replace the need for runbooks',
          'The team that owns the system also owns the record of why it is the way it is',
          'Operational teams refuse to take over systems without ADRs',
        ],
        correctIndex: 2,
        explanation: 'Autonomous delivery teams benefit most when the "why" travels with the code — the same people who ship it live with the consequences and write them down.',
      },
      {
        id: 'adr-h3',
        difficulty: 'hard',
        question: 'What is the primary intent of the Status field on an ADR (proposed / accepted / superseded)?',
        choices: [
          'To trigger an approval workflow in a ticket system',
          'To let readers tell at a glance which decisions are current and which are history',
          'To grant the author editing rights',
          'To determine code review ownership',
        ],
        correctIndex: 1,
        explanation: 'Status makes the lifecycle of a decision legible: readers can immediately see whether an ADR represents the current design or a chapter in its history.',
      },
      // ---- EASY (additional) ----
      {
        id: 'adr-e4',
        difficulty: 'easy',
        question: 'Who is generally credited with proposing the lightweight ADR format in 2011?',
        choices: ['Martin Fowler', 'Michael Nygard', 'Gregor Hohpe', 'Simon Brown'],
        correctIndex: 1,
        explanation: 'Michael Nygard proposed lightweight ADRs in his 2011 post "Documenting Architecture Decisions" as an alternative to heavyweight architecture documents.',
      },
      {
        id: 'adr-e5',
        difficulty: 'easy',
        question: 'Which of these is a valid ADR status?',
        choices: [
          'Open, In Progress, Closed',
          'Proposed, Accepted, Superseded',
          'Draft, Review, Published',
          'New, Active, Archived',
        ],
        correctIndex: 1,
        explanation: 'ADR statuses are: Proposed (under discussion), Accepted (current decision), and Superseded (replaced by a newer ADR).',
      },
      {
        id: 'adr-e6',
        difficulty: 'easy',
        question: 'What does the "Context" section of an ADR capture?',
        choices: [
          'The code changes made to implement the decision',
          'The forces in play that made the decision necessary',
          'The team members involved in the discussion',
          'The budget allocated for the decision',
        ],
        correctIndex: 1,
        explanation: 'Context captures the background: the forces, constraints, and situation that made the decision necessary in the first place.',
      },
      {
        id: 'adr-e7',
        difficulty: 'easy',
        question: 'What is the purpose of numbering ADRs sequentially?',
        choices: [
          'To rank decisions by importance',
          'To provide a unique identifier and show the chronological order of decisions',
          'To allocate review bandwidth among team members',
          'To set priority for implementation order',
        ],
        correctIndex: 1,
        explanation: 'Sequential numbering gives each ADR a stable reference (e.g. "see ADR-0012") and makes the history of decisions easy to navigate.',
      },
      {
        id: 'adr-e8',
        difficulty: 'easy',
        question: 'An ADR\'s "Decision" section states:',
        choices: [
          'The problem background and forces in play',
          'What was chosen, stated clearly and unambiguously',
          'Who made the decision and when',
          'When the decision will next be reviewed',
        ],
        correctIndex: 1,
        explanation: 'The Decision section is a clear statement of what was chosen \u2014 not the context or consequences, just the choice itself.',
      },
      {
        id: 'adr-e9',
        difficulty: 'easy',
        question: 'How long is a typical ADR supposed to be?',
        choices: [
          '10\u201320 pages with full design rationale',
          'One page \u2014 short and focused on one decision',
          'As long as needed for comprehensive documentation',
          '3\u20135 pages covering all related decisions',
        ],
        correctIndex: 1,
        explanation: 'ADRs are intentionally one page: short enough to actually be written during the decision, and read by future team members.',
      },
      {
        id: 'adr-e10',
        difficulty: 'easy',
        question: 'What problem do ADRs solve six months after a decision is made?',
        choices: [
          'They automate rollback of bad decisions',
          'They preserve the "why" behind decisions so future teams can understand, re-evaluate, or intentionally replace them',
          'They measure the quality of architectural decisions',
          'They enforce consistency across teams',
        ],
        correctIndex: 1,
        explanation: 'Without ADRs, the reasoning behind past decisions is lost. New joiners re-open old debates; teams waste time second-guessing well-considered choices.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'adr-m4',
        difficulty: 'medium',
        question: 'A team discovers that ADR-005 (use REST APIs) is no longer appropriate as they now need event-driven communication. The correct action is:',
        choices: [
          'Edit ADR-005 to change it to event-driven',
          'Delete ADR-005 and create a fresh replacement',
          'Write a new ADR that supersedes ADR-005 and mark ADR-005 as superseded',
          'Archive ADR-005 in a separate folder without a replacement',
        ],
        correctIndex: 2,
        explanation: 'ADRs are immutable. Write a new ADR referencing the old one, mark the old one superseded, and preserve the full history of the thinking.',
      },
      {
        id: 'adr-m5',
        difficulty: 'medium',
        question: 'Which scenario best illustrates why ADRs prevent "reopening old debates"?',
        choices: [
          'A new team member asks "why PostgreSQL?" \u2014 the ADR gives the context, options considered, and trade-offs accepted at the time',
          'The CTO has an excellent memory for past decisions',
          'A ticketing system tracks which decisions were made',
          'All team members were present when every decision was made',
        ],
        correctIndex: 0,
        explanation: 'The ADR acts as institutional memory: the new joiner gets the full context of the decision without needing to gather it from people who may have left.',
      },
      {
        id: 'adr-m6',
        difficulty: 'medium',
        question: 'Why is the Consequences section more valuable than the Decision section for future readers?',
        choices: [
          'Because the decision is usually obvious in hindsight',
          'Because consequences show what trade-offs were accepted, helping future teams understand what they are working within',
          'Because the decision section is usually incorrect',
          'Because consequences are easier and faster to write',
        ],
        correctIndex: 1,
        explanation: 'Future readers need to know what the decision constrains, enables, and risks \u2014 not just what was chosen, but what living with it means.',
      },
      {
        id: 'adr-m7',
        difficulty: 'medium',
        question: 'Who should ideally write an ADR, according to the deep dive?',
        choices: [
          'Only the chief architect',
          'Anyone making the decision \u2014 architect, tech lead, or the team itself',
          'A dedicated technical writing team',
          'The project manager after the decision is finalised',
        ],
        correctIndex: 1,
        explanation: 'ADRs work best when written by the people making the decision, capturing live context \u2014 not delegated to a separate documentation role.',
      },
      {
        id: 'adr-m8',
        difficulty: 'medium',
        question: 'A team writes "We chose PostgreSQL AND Redis AND Kafka" in a single ADR. What is wrong with this?',
        choices: [
          'Nothing \u2014 comprehensive ADRs are more useful',
          'It violates the "one ADR = one decision" principle; these should be three separate ADRs',
          'Using three technologies is too complex for a single system',
          'Kafka is not an architectural decision',
        ],
        correctIndex: 1,
        explanation: 'Small, focused ADRs are easier to read, easier to supersede individually, and easier to search for later. One decision per ADR is the rule.',
      },
      {
        id: 'adr-m9',
        difficulty: 'medium',
        question: 'When is the ideal time to write an ADR?',
        choices: [
          'A week after the decision, when the dust has settled',
          'During the decision meeting itself \u2014 as a working document capturing live context',
          'During the annual architecture review',
          'After the feature implementing the decision has shipped',
        ],
        correctIndex: 1,
        explanation: 'Writing during the meeting captures the actual options, the live trade-off reasoning, and the real context \u2014 all of which erode quickly after the fact.',
      },
      {
        id: 'adr-m10',
        difficulty: 'medium',
        question: 'What does "append-only" mean for an ADR repository?',
        choices: [
          'You can only add text to an ADR, never delete any',
          'New information or changed decisions require a new ADR; old ADRs are never edited',
          'ADRs are stored in append-only databases',
          'Only one person can contribute to each ADR',
        ],
        correctIndex: 1,
        explanation: 'Append-only preserves the full historical record. The sequence of ADRs tells the story of how the architecture evolved and why.',
      },
      // ---- HARD (additional) ----
      {
        id: 'adr-h4',
        difficulty: 'hard',
        question: 'According to the deep dive, a "retrospective artefact" ADR (filled in after the fact) is inferior because:',
        choices: [
          'It is harder to format correctly',
          'It loses the live context, options considered, and reasoning that only exist during the actual decision moment',
          'The team has already forgotten all the alternatives by then',
          'Retrospective ADRs are always too long',
        ],
        correctIndex: 1,
        explanation: 'The value of an ADR is its capture of live thinking. Written retrospectively, it becomes a rationalisation rather than a record of what was actually considered.',
      },
      {
        id: 'adr-h5',
        difficulty: 'hard',
        question: 'Why does ADR immutability specifically preserve the history of thinking?',
        choices: [
          'Because immutable files physically cannot be deleted',
          'Because future readers can see what was true at the time of each decision and why each subsequent ADR was necessary',
          'Because git history alone is insufficient for this purpose',
          'Because regulations require it',
        ],
        correctIndex: 1,
        explanation: 'The sequence of ADRs and their superseding relationships shows how the architecture evolved \u2014 which is impossible to reconstruct if old ADRs are overwritten.',
      },
      {
        id: 'adr-h6',
        difficulty: 'hard',
        question: 'The deep dive says "Consequences matter more than the decision." What evidence supports this claim?',
        choices: [
          'The Consequences section is always shorter and therefore easier to scan',
          'Writing consequences forces the author to acknowledge trade-offs \u2014 the information future readers most need',
          'Consequences are more factual than decisions and therefore more reliable',
          'Consequences are the only section that cannot be superseded',
        ],
        correctIndex: 1,
        explanation: 'The decision is history; the consequences are what future teams live with. Acknowledging trade-offs explicitly prevents the ADR from pretending a silver bullet was found.',
      },
      {
        id: 'adr-h7',
        difficulty: 'hard',
        question: 'Why were lightweight ADRs proposed as an alternative to heavyweight architecture documents?',
        choices: [
          'Lightweight documents are always preferable to heavyweight ones',
          'Heavyweight docs become outdated quickly and are rarely read; lightweight ADRs stay small enough to remain current and useful',
          'ADRs require less formal formatting than architecture documents',
          'Architects simply prefer shorter documents',
        ],
        correctIndex: 1,
        explanation: 'A 50-page architecture document no-one reads provides no value. A one-page ADR that teams actually write, read, and refer to provides compounding value.',
      },
      {
        id: 'adr-h8',
        difficulty: 'hard',
        question: 'ADR-022 has status "superseded by ADR-037." What status does ADR-037 most likely carry?',
        choices: [
          'Also superseded by a later ADR',
          'Proposed \u2014 it is still under discussion',
          'Accepted \u2014 it is the current active decision',
          'Archived \u2014 it is no longer relevant',
        ],
        correctIndex: 2,
        explanation: 'ADR-037 supersedes ADR-022, so it should be the currently accepted decision. Accepted means it represents the current architectural choice.',
      },
      {
        id: 'adr-h9',
        difficulty: 'hard',
        question: 'How do ADRs complement "You build it, you run it" specifically?',
        choices: [
          'They reduce the number of deployment decisions a team must make',
          'The team that owns and operates the system also owns the record of why it was built that way \u2014 accountability follows the code',
          'They automate operational decision-making',
          'ADRs replace runbooks for common operational procedures',
        ],
        correctIndex: 1,
        explanation: 'YBYR gives teams end-to-end ownership. ADRs ensure the "why" travels with that ownership \u2014 the team is accountable for both the decisions and their consequences.',
      },
      {
        id: 'adr-h10',
        difficulty: 'hard',
        question: 'What distinguishes an ADR written as a "working document" from one written retrospectively?',
        choices: [
          'Working documents are always longer and more detailed',
          'Working documents capture the actual options and reasoning as they existed during the decision; retrospective ones often rationalise choices after the fact',
          'Working documents require more formal approvals',
          'Working documents use a different template structure',
        ],
        correctIndex: 1,
        explanation: 'A working document is a live record of the decision process. A retrospective one reconstructs it from memory \u2014 losing the options that were rejected and the reasoning that was live.',
      },
    ],
  },
};
