import { QuizDefinition } from './types';

/** Quizzes for the Platform Team floor (left room of floor 1). */
export const QUIZ_PLATFORM: Record<string, QuizDefinition> = {
  /* --------------------------------------------------------- */
  /*  Platform Engineering                                      */
  /* --------------------------------------------------------- */
  'platform-engineering': {
    infoId: 'platform-engineering',
    questions: [
      // ---- EASY ----
      {
        id: 'pe-e1',
        difficulty: 'easy',
        question: 'What does IDP stand for in the context of Platform Engineering?',
        choices: [
          'Internet Data Protocol',
          'Internal Developer Platform',
          'Integrated Deployment Pipeline',
          'Infrastructure Design Pattern',
        ],
        correctIndex: 1,
        explanation: 'IDP stands for Internal Developer Platform — a self-service layer for development teams.',
      },
      {
        id: 'pe-e2',
        difficulty: 'easy',
        question: 'What are "golden paths" in platform engineering?',
        choices: [
          'Physical pathways in the office',
          'Pre-configured, opinionated workflows that encode best practices',
          'Premium-tier cloud service plans',
          'Network routing protocols',
        ],
        correctIndex: 1,
        explanation: 'Golden paths are pre-configured workflows that encode best practices while still allowing flexibility.',
      },
      {
        id: 'pe-e3',
        difficulty: 'easy',
        question: 'What key principle does a platform team follow regarding development teams?',
        choices: [
          'All code must be reviewed by the platform team',
          'Development teams should never touch infrastructure',
          'Reduce cognitive load so teams focus on business logic',
          'Every team must use the same programming language',
        ],
        correctIndex: 2,
        explanation: 'The platform reduces cognitive load on development teams so they can focus on business logic rather than infrastructure plumbing.',
      },
      // ---- MEDIUM ----
      {
        id: 'pe-m1',
        difficulty: 'medium',
        question: 'Instead of every team building their own CI/CD pipelines, what does a platform team provide?',
        choices: [
          'A mandate that no CI/CD is needed',
          'Pre-configured, reusable golden path workflows',
          'A single monolithic deployment pipeline for all teams',
          'Outsourced DevOps consulting',
        ],
        correctIndex: 1,
        explanation: 'Platform teams create golden paths — reusable, pre-configured workflows — so individual teams don\'t reinvent the wheel.',
      },
      {
        id: 'pe-m2',
        difficulty: 'medium',
        question: 'What is the combined philosophy behind platform engineering?',
        choices: [
          '"Move fast and break things"',
          '"You build it, you run it" combined with "We make running it easy"',
          '"Don\'t repeat yourself" and "Keep it simple"',
          '"Fail fast" and "Ship often"',
        ],
        correctIndex: 1,
        explanation: 'Platform engineering combines ownership ("you build it, you run it") with support ("we make running it easy").',
      },
      {
        id: 'pe-m3',
        difficulty: 'medium',
        question: 'What is an anti-pattern in platform engineering?',
        choices: [
          'Making the platform optional',
          'Starting with a small platform',
          'Mandating platform use without providing value',
          'Measuring developer satisfaction',
        ],
        correctIndex: 2,
        explanation: 'Forcing teams to use a platform that doesn\'t provide clear value is a common anti-pattern that breeds resentment.',
      },
      // ---- HARD ----
      {
        id: 'pe-h1',
        difficulty: 'hard',
        question: 'According to Team Topologies, what is a Platform Team\'s primary interaction mode?',
        choices: [
          'Collaboration',
          'Facilitation',
          'X-as-a-Service',
          'Pair programming',
        ],
        correctIndex: 2,
        explanation: 'Platform Teams provide capabilities via "X-as-a-Service" — teams consume with minimal coordination.',
      },
      {
        id: 'pe-h2',
        difficulty: 'hard',
        question: 'What is the "Thinnest Viable Platform" (TVP) concept?',
        choices: [
          'Using the cheapest possible cloud provider',
          'Starting with the smallest platform that provides value, possibly just documentation',
          'Removing all features except deployment',
          'Running on the minimum number of servers',
        ],
        correctIndex: 1,
        explanation: 'TVP means starting small — even a wiki page with best practices — and evolving toward self-service APIs as needs grow.',
      },
      {
        id: 'pe-h3',
        difficulty: 'hard',
        question: 'Which of these is a key metric for platform success according to the deep dive?',
        choices: [
          'Lines of code written per day',
          'Number of microservices deployed',
          'Developer onboarding time and developer satisfaction',
          'Total number of cloud resources provisioned',
        ],
        correctIndex: 2,
        explanation: 'Key metrics include onboarding time, time to first deploy, change failure rate, and developer satisfaction surveys.',
      },
      // ---- EASY (additional) ----
      {
        id: 'pe-e4',
        difficulty: 'easy',
        question: 'Which book is a primary theoretical foundation of Platform Engineering?',
        choices: [
          '"Clean Code" by Robert C. Martin',
          '"Team Topologies" by Skelton and Pais',
          '"The Phoenix Project" by Gene Kim',
          '"Accelerate" by Nicole Forsgren',
        ],
        correctIndex: 1,
        explanation: 'Team Topologies by Matthew Skelton and Manuel Pais defines four team types, including the Platform team and its X-as-a-Service interaction mode.',
      },
      {
        id: 'pe-e5',
        difficulty: 'easy',
        question: 'How many fundamental team types does Team Topologies identify?',
        choices: ['Two', 'Three', 'Four', 'Six'],
        correctIndex: 2,
        explanation: 'Team Topologies defines four team types: Stream-aligned, Enabling, Complicated Subsystem, and Platform.',
      },
      {
        id: 'pe-e6',
        difficulty: 'easy',
        question: 'Which of these is NOT one of the four team types in Team Topologies?',
        choices: ['Stream-aligned', 'Enabling', 'Architecture', 'Complicated Subsystem'],
        correctIndex: 2,
        explanation: '"Architecture team" is not one of the four Team Topologies types. The four are: Stream-aligned, Enabling, Complicated Subsystem, and Platform.',
      },
      {
        id: 'pe-e7',
        difficulty: 'easy',
        question: 'What does a Platform team provide to enable "You build it, you run it"?',
        choices: [
          'A separate operations team to handle production incidents',
          'A self-service platform that reduces the cognitive load of owning services',
          'Code reviews for every production deployment',
          'Mandatory training on cloud infrastructure',
        ],
        correctIndex: 1,
        explanation: 'The platform makes "running it easy" so product teams can own their services without being overwhelmed by infrastructure complexity.',
      },
      {
        id: 'pe-e8',
        difficulty: 'easy',
        question: 'Without golden paths, what problem does each development team face?',
        choices: [
          'They cannot write tests',
          'Every team must reinvent CI/CD, monitoring, and infrastructure from scratch',
          'Teams cannot deploy independently',
          'Teams must use the same programming language',
        ],
        correctIndex: 1,
        explanation: 'Without golden paths, every team reinvents the same infrastructure \u2014 creating inconsistency and wasting effort on undifferentiated work.',
      },
      {
        id: 'pe-e9',
        difficulty: 'easy',
        question: 'What does "self-service" mean in the context of an Internal Developer Platform?',
        choices: [
          'Teams write all their own tools',
          'Teams can provision infrastructure and run workflows without waiting for the platform team',
          'Developers interview and hire themselves',
          'Teams manage their own payroll systems',
        ],
        correctIndex: 1,
        explanation: 'Self-service means teams access platform capabilities on demand \u2014 no tickets, no waiting for a human in the platform team to act.',
      },
      {
        id: 'pe-e10',
        difficulty: 'easy',
        question: 'What is the primary goal of reducing cognitive load on development teams?',
        choices: [
          'To make developers work fewer hours',
          'To let teams focus on business logic and product delivery instead of infrastructure plumbing',
          'To reduce the number of engineers needed',
          'To simplify the codebase',
        ],
        correctIndex: 1,
        explanation: 'Cognitive load reduction means developers can focus on the unique value they create \u2014 the business problem \u2014 rather than infrastructure boilerplate.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'pe-m4',
        difficulty: 'medium',
        question: 'A developer needs a new database environment for testing. In an ideal Platform Engineering setup, they should:',
        choices: [
          'Open a ticket and wait for the platform team to provision it',
          'Provision it themselves via a self-service API with no coordination needed',
          'Ask their manager to escalate to ops',
          'Use their local laptop instead',
        ],
        correctIndex: 1,
        explanation: 'X-as-a-Service means stream-aligned teams consume platform capabilities on demand \u2014 self-service with minimal coordination.',
      },
      {
        id: 'pe-m5',
        difficulty: 'medium',
        question: 'Which scenario is an example of the "mandating platform use without providing value" anti-pattern?',
        choices: [
          'Requiring teams to use a platform that halves their deployment time',
          'Forcing teams to use a slow, unreliable CI/CD system with no alternative',
          'Providing a golden path that most teams adopt voluntarily',
          'Offering optional platform tooling with good documentation',
        ],
        correctIndex: 1,
        explanation: 'Forcing adoption of a platform that slows teams down breeds resentment and resistance \u2014 the opposite of what Platform Engineering aims for.',
      },
      {
        id: 'pe-m6',
        difficulty: 'medium',
        question: 'What is the key reason a Platform team should treat its platform as a "product"?',
        choices: [
          'It generates direct revenue for the company',
          'It has internal customers whose feedback should shape its features and evolution',
          'Products have better tooling than platforms',
          'It helps justify the platform team\'s headcount',
        ],
        correctIndex: 1,
        explanation: 'Treating the platform as a product means understanding developer needs, gathering feedback, and iterating \u2014 just like any customer-facing product.',
      },
      {
        id: 'pe-m7',
        difficulty: 'medium',
        question: 'Why is measuring "developer onboarding time" a useful platform metric?',
        choices: [
          'It measures the quality of the HR hiring process',
          'It reveals whether the platform truly makes it easy for new engineers to become productive quickly',
          'It tracks how fast developers learn to program',
          'It measures documentation quality in isolation',
        ],
        correctIndex: 1,
        explanation: 'Onboarding time reflects the platform\'s ability to make new engineers productive quickly \u2014 a direct signal of self-service quality.',
      },
      {
        id: 'pe-m8',
        difficulty: 'medium',
        question: 'A stream-aligned team wants to use a technology not covered by any golden path. What should the platform team\'s response be?',
        choices: [
          'Refuse \u2014 all teams must use golden paths strictly',
          'Mandate they adopt an existing path regardless of fit',
          'Golden paths are opinionated but flexible; support the team in making an appropriate choice',
          'Transfer the team to a different business unit',
        ],
        correctIndex: 2,
        explanation: 'Golden paths provide defaults and best practices but are not prisons \u2014 allowing flexibility while encoding opinions is core to the design.',
      },
      {
        id: 'pe-m9',
        difficulty: 'medium',
        question: 'What distinguishes a Platform team\'s interaction mode from an Enabling team\'s?',
        choices: [
          'Platform teams pair-program with stream-aligned teams; Enabling teams don\'t',
          'Platform teams provide X-as-a-Service (minimal coordination); Enabling teams facilitate and upskill (temporary collaboration)',
          'Enabling teams are always larger than Platform teams',
          'Platform teams are owned by IT; Enabling teams by engineering',
        ],
        correctIndex: 1,
        explanation: 'X-as-a-Service means minimum coordination; facilitation means active collaboration to raise capability. These are distinct interaction modes in Team Topologies.',
      },
      {
        id: 'pe-m10',
        difficulty: 'medium',
        question: 'What does "building too much too early" risk in a Platform Engineering context?',
        choices: [
          'Building a platform that is too fast to use',
          'Overinvesting in features nobody needs yet, delaying value delivery and creating a maintenance burden',
          'Creating security vulnerabilities',
          'Hiring too many platform engineers',
        ],
        correctIndex: 1,
        explanation: 'The Thinnest Viable Platform principle guards against this: start with what provides value now and evolve based on actual demand.',
      },
      // ---- HARD (additional) ----
      {
        id: 'pe-h4',
        difficulty: 'hard',
        question: 'The four team types in Team Topologies, in full, are:',
        choices: [
          'Product, Dev, Ops, QA',
          'Frontend, Backend, Infrastructure, Security',
          'Stream-aligned, Enabling, Complicated Subsystem, Platform',
          'Feature, Support, Architecture, Operations',
        ],
        correctIndex: 2,
        explanation: 'Team Topologies identifies exactly four types: Stream-aligned (delivery), Enabling (upskilling), Complicated Subsystem (specialist knowledge), and Platform (X-as-a-Service).',
      },
      {
        id: 'pe-h5',
        difficulty: 'hard',
        question: 'According to the deep dive, which signal most directly indicates that developers actually value the platform?',
        choices: [
          'The number of golden paths defined',
          'The size of the platform engineering team',
          'Voluntary adoption \u2014 developers choose to use it without being mandated',
          'The number of cloud resources the platform manages',
        ],
        correctIndex: 2,
        explanation: 'A good platform is one developers voluntarily choose \u2014 forced adoption masks whether the platform actually helps.',
      },
      {
        id: 'pe-h6',
        difficulty: 'hard',
        question: 'The deep dive identifies "treating the platform as a pure infrastructure concern" as an anti-pattern. What should it be treated as instead?',
        choices: [
          'A security system',
          'A cost center',
          'A product with internal customers',
          'A compliance tool',
        ],
        correctIndex: 2,
        explanation: 'A platform that ignores its users\' experience fails. Treating it as a product means continuous discovery of developer needs and iterating on the offering.',
      },
      {
        id: 'pe-h7',
        difficulty: 'hard',
        question: 'Which of the following is explicitly cited as a key platform success metric in the deep dive?',
        choices: [
          'Cost per cloud resource',
          'Number of microservices deployed',
          'Time to first deploy',
          'Lines of platform code written',
        ],
        correctIndex: 2,
        explanation: 'Time to first deploy \u2014 how quickly a new team can ship to production \u2014 is a direct indicator of how well the platform reduces friction.',
      },
      {
        id: 'pe-h8',
        difficulty: 'hard',
        question: 'What distinguishes the "Complicated Subsystem" team type from a Platform team?',
        choices: [
          'Complicated Subsystem teams provide infrastructure; Platform teams provide expertise',
          'Complicated Subsystem teams own deep specialist knowledge for a complex domain; Platform teams provide broad self-service capabilities',
          'Platform teams are always larger',
          'Complicated Subsystem teams use X-as-a-Service',
        ],
        correctIndex: 1,
        explanation: 'Complicated Subsystem teams exist for genuinely complex technical domains requiring deep expertise (e.g. video encoding). Platform teams provide broad, reusable capabilities as a service.',
      },
      {
        id: 'pe-h9',
        difficulty: 'hard',
        question: 'The "Thinnest Viable Platform" can start as just a wiki page. What principle does this reflect?',
        choices: [
          'Documentation is always more important than code',
          'Platform Engineering doesn\'t require any tooling',
          'Start with the minimum that provides real value and evolve incrementally based on proven demand',
          'Wikis are the best developer tooling available',
        ],
        correctIndex: 2,
        explanation: 'TVP is a lean approach: deliver value immediately with minimal investment, then add self-service APIs, portals, and automation as actual needs emerge.',
      },
      {
        id: 'pe-h10',
        difficulty: 'hard',
        question: 'According to Team Topologies, what is the "cognitive load" problem that Platform teams are specifically designed to solve for stream-aligned teams?',
        choices: [
          'Too many programming languages to learn',
          'The burden of managing infrastructure, tooling, and operational complexity on top of delivering product features',
          'Too many meetings with stakeholders',
          'Having too many microservices to maintain',
        ],
        correctIndex: 1,
        explanation: 'Stream-aligned teams focus on delivering value; offloading infrastructure complexity to a Platform team keeps that cognitive load within manageable bounds.',
      },
    ],
  },

  /* --------------------------------------------------------- */
  /*  You Build It, You Run It                                  */
  /* --------------------------------------------------------- */
  'you-build-you-run': {
    infoId: 'you-build-you-run',
    questions: [
      // ---- EASY ----
      {
        id: 'ybyr-e1',
        difficulty: 'easy',
        question: 'Who coined the phrase "You build it, you run it"?',
        choices: [
          'Martin Fowler',
          'Werner Vogels (Amazon CTO)',
          'Kent Beck',
          'Gene Kim',
        ],
        correctIndex: 1,
        explanation: 'Werner Vogels coined the phrase in a 2006 ACM Queue interview to describe how AWS teams work.',
      },
      {
        id: 'ybyr-e2',
        difficulty: 'easy',
        question: 'In "you build it, you run it," who carries the pager when a service breaks in production?',
        choices: [
          'A separate 24/7 operations team',
          'The developers who wrote the service',
          'The security team',
          'The CTO',
        ],
        correctIndex: 1,
        explanation: 'The team that built the service also operates it — closing the feedback loop between design and production behaviour.',
      },
      {
        id: 'ybyr-e3',
        difficulty: 'easy',
        question: 'Which model does "you build it, you run it" replace?',
        choices: [
          'Agile sprints',
          'Test-driven development',
          'The "throw code over the wall" handoff between dev and ops',
          'Pair programming',
        ],
        correctIndex: 2,
        explanation: 'It replaces the old relay race where developers handed finished code to a separate ops team that hadn\'t designed it.',
      },
      // ---- MEDIUM ----
      {
        id: 'ybyr-m1',
        difficulty: 'medium',
        question: 'Why does being on-call for your own service tend to improve its design?',
        choices: [
          'It forces developers to work longer hours',
          'On-call hours count toward performance reviews',
          'When you personally get paged at 3 a.m., you invest in reliability and fix root causes',
          'On-call rotations generate more commits',
        ],
        correctIndex: 2,
        explanation: 'The pager is a direct feedback signal: pain felt by the author becomes reliability improvements in the next release.',
      },
      {
        id: 'ybyr-m2',
        difficulty: 'medium',
        question: 'Which advantage for a dev team does "you build it, you run it" NOT directly provide?',
        choices: [
          'Faster feedback from production',
          'Tighter ownership and autonomy',
          'A guarantee that the team never needs other teams',
          'Growth of SRE / deployment skills across the team',
        ],
        correctIndex: 2,
        explanation: 'Ownership is end-to-end, but teams still collaborate — typically with a Platform team that makes "running it" easy.',
      },
      {
        id: 'ybyr-m3',
        difficulty: 'medium',
        question: 'Which real-world analogy best captures "you build it, you run it"?',
        choices: [
          'A novelist who hires a ghostwriter',
          'A restaurant chef who also works the dining room and hears customers directly',
          'A courier who only delivers pre-packaged boxes',
          'A librarian organizing other people\'s books',
        ],
        correctIndex: 1,
        explanation: 'The chef hears complaints in real time and iterates the menu — a tight feedback loop the factory-canteen model lacks.',
      },
      // ---- HARD ----
      {
        id: 'ybyr-h1',
        difficulty: 'hard',
        question: 'Which research programme links end-to-end team ownership to the "four key metrics" (deployment frequency, lead time, change failure rate, MTTR)?',
        choices: [
          'ISO 9001',
          'DORA / State of DevOps (Accelerate)',
          'ITIL',
          'CMMI',
        ],
        correctIndex: 1,
        explanation: 'DORA\'s Accelerate research shows teams practicing "you build it, you run it" consistently outperform on all four key delivery metrics.',
      },
      {
        id: 'ybyr-h2',
        difficulty: 'hard',
        question: 'What is the main risk of adopting "you build it, you run it" without a supporting Platform team?',
        choices: [
          'Developers become too specialized in one area',
          'Cognitive overload — every team must also master Kubernetes, tracing and incident response',
          'Code reviews become mandatory',
          'Services are deployed too infrequently',
        ],
        correctIndex: 1,
        explanation: 'Without a "thinnest viable platform" to reduce cognitive load, full ownership can crush product teams — Team Topologies pairs the two patterns deliberately.',
      },
      {
        id: 'ybyr-h3',
        difficulty: 'hard',
        question: 'Which complementary practice is NOT typically listed alongside "you build it, you run it"?',
        choices: [
          'Blameless post-mortems and error budgets',
          'Feature flags and progressive (canary / blue-green) deployment',
          'Production-grade observability built in from day one',
          'Quarterly "big bang" release windows managed by a change board',
        ],
        correctIndex: 3,
        explanation: 'Quarterly change-board releases are the opposite pattern — they recreate the dev/ops wall the principle is designed to remove.',
      },
      // ---- EASY (additional) ----
      {
        id: 'ybyr-e4',
        difficulty: 'easy',
        question: 'In what year did Werner Vogels describe "You build it, you run it" in ACM Queue?',
        choices: ['1998', '2002', '2006', '2010'],
        correctIndex: 2,
        explanation: 'Werner Vogels described the approach in a 2006 ACM Queue interview about how AWS teams operate.',
      },
      {
        id: 'ybyr-e5',
        difficulty: 'easy',
        question: '"You build it, you run it" is primarily about closing which gap?',
        choices: [
          'The gap between frontend and backend teams',
          'The gap between developers and the operational reality of their software',
          'The gap between senior and junior engineers',
          'The gap between engineering and HR',
        ],
        correctIndex: 1,
        explanation: 'The principle closes the loop between writing software and operating it in production \u2014 making developers feel the consequences of their own decisions.',
      },
      {
        id: 'ybyr-e6',
        difficulty: 'easy',
        question: 'Which of these is part of "end-to-end ownership" in "You build it, you run it"?',
        choices: [
          'Only writing and testing the code',
          'Only deploying the code to staging',
          'Design, code, CI/CD, deployment, observability, on-call, and post-incident learning',
          'Writing code and handing it to a separate ops team',
        ],
        correctIndex: 2,
        explanation: 'End-to-end ownership means the team is responsible for the full lifecycle \u2014 from design through to post-incident reviews.',
      },
      {
        id: 'ybyr-e7',
        difficulty: 'easy',
        question: 'What was the key problem with the old "relay race" development model?',
        choices: [
          'It was too fast for organizations to manage',
          'Developers handed code to ops who hadn\'t designed it \u2014 ops couldn\'t diagnose problems; developers didn\'t feel the pain',
          'Ops teams were less skilled than developers',
          'It required too many project managers',
        ],
        correctIndex: 1,
        explanation: 'In the relay race, responsibility was split: devs wrote code they didn\'t run; ops ran code they didn\'t write. Incidents dragged because understanding and accountability were separated.',
      },
      {
        id: 'ybyr-e8',
        difficulty: 'easy',
        question: 'How does "You build it, you run it" improve the quality of technical design?',
        choices: [
          'By requiring more code reviews',
          'By giving developers financial incentives for reliability',
          'When you get paged for your own service\'s failures, you stop shipping code that causes them',
          'By assigning dedicated QA engineers to each team',
        ],
        correctIndex: 2,
        explanation: 'On-call is a powerful design signal: pain caused by your own code motivates you to fix root causes and build reliability in from the start.',
      },
      {
        id: 'ybyr-e9',
        difficulty: 'easy',
        question: 'What skills do developers gain through "You build it, you run it"?',
        choices: [
          'Primarily UI/UX design skills',
          'Deployment, monitoring, and SRE skills that make them stronger engineers',
          'Marketing and sales skills',
          'Project management certifications',
        ],
        correctIndex: 1,
        explanation: 'End-to-end ownership exposes developers to the full operational landscape, growing skills in deployment, observability, and incident response.',
      },
      {
        id: 'ybyr-e10',
        difficulty: 'easy',
        question: 'What does "clear ownership" mean in the context of "You build it, you run it"?',
        choices: [
          'One developer owns all the code',
          'One team is accountable for outcomes, not just outputs',
          'One manager signs off on all changes',
          'One repository per team',
        ],
        correctIndex: 1,
        explanation: 'Clear ownership means one team is accountable end-to-end \u2014 for how the service performs in production, not just whether the code compiles.',
      },
      // ---- MEDIUM (additional) ----
      {
        id: 'ybyr-m4',
        difficulty: 'medium',
        question: 'A team is on-call for their own service and notices the same alert fires every Monday morning. What should they do under "You build it, you run it"?',
        choices: [
          'Accept it as normal maintenance overhead',
          'Escalate to the ops team for investigation',
          'Fix the root cause \u2014 they have both the authority and the motivation to do so',
          'Mute the alert until the next quarter\'s prioritization',
        ],
        correctIndex: 2,
        explanation: 'The on-call rotation is a feedback signal. The team that owns the service is in the best position \u2014 and has the strongest motivation \u2014 to fix root causes, not just escalate.',
      },
      {
        id: 'ybyr-m5',
        difficulty: 'medium',
        question: 'What does "autonomy" specifically mean for a team practicing "You build it, you run it"?',
        choices: [
          'The team works without any coordination with other teams',
          'No tickets to another team, no handoff delays \u2014 the team controls its own deployment decisions',
          'The team has no technical standards to follow',
          'Developers choose their own compensation',
        ],
        correctIndex: 1,
        explanation: 'Autonomy means the team controls its own destiny: no waiting for ops approvals, no handoff queues \u2014 the same people who build can deploy and iterate.',
      },
      {
        id: 'ybyr-m6',
        difficulty: 'medium',
        question: 'Why does "You build it, you run it" lead to "pride of craftsmanship"?',
        choices: [
          'Because teams are evaluated on code quality metrics',
          'Because when you own outcomes end-to-end \u2014 not just outputs \u2014 you care whether the service actually works well in production',
          'Because managers reward quality more under this model',
          'Because the team presents their work to the CEO',
        ],
        correctIndex: 1,
        explanation: 'Owning outcomes means the team sees the full picture including failures. That accountability and visibility restores pride in the quality of the work.',
      },
      {
        id: 'ybyr-m7',
        difficulty: 'medium',
        question: 'Which scenario best illustrates why "You build it, you run it" breaks down WITHOUT platform support?',
        choices: [
          'A team deploys to staging without running tests',
          'A team must also master Kubernetes, distributed tracing, and incident response simultaneously \u2014 leaving no capacity for product work',
          'A team ships features too infrequently',
          'A team has no QA engineer',
        ],
        correctIndex: 1,
        explanation: 'Without a platform to absorb infrastructure complexity, full ownership becomes cognitive overload \u2014 defeating the purpose of the principle.',
      },
      {
        id: 'ybyr-m8',
        difficulty: 'medium',
        question: 'How does "You build it, you run it" change the relationship between code quality and developer incentives?',
        choices: [
          'Code quality becomes a management concern only',
          'Developers are paid more for reliable code',
          'Poor reliability means worse on-call for the authors, so reliability becomes a first-class design goal from the start',
          'Quality gates are enforced entirely by the build system',
        ],
        correctIndex: 2,
        explanation: 'Unlike the relay-race model where devs never feel production pain, YBYR makes poor reliability personally painful for its authors \u2014 aligning incentives powerfully.',
      },
      {
        id: 'ybyr-m9',
        difficulty: 'medium',
        question: 'What does "pager fatigue" refer to, and why is it a risk under "You build it, you run it"?',
        choices: [
          'Fatigue from carrying heavy physical pagers',
          'Burnout caused by excessive on-call alerts without good tooling or rotation \u2014 unsustainable over time',
          'Alert desensitization from too many monitoring dashboards',
          'Developers refusing to participate in on-call at all',
        ],
        correctIndex: 1,
        explanation: 'Pager fatigue occurs when on-call becomes a constant burden \u2014 poor alert hygiene, no follow-the-sun rotation, and insufficient tooling turn ownership into punishment.',
      },
      {
        id: 'ybyr-m10',
        difficulty: 'medium',
        question: 'The info content says YBYR is "less a process than a feedback loop." What does this mean?',
        choices: [
          'It cannot be documented or standardized',
          'The value isn\'t in the process steps but in the continuous signal flowing from operational reality back to design decisions',
          'Feedback loops require automated testing only',
          'It means retrospectives are more important than releases',
        ],
        correctIndex: 1,
        explanation: 'The insight is that YBYR\'s value is systemic: every architectural decision receives an operational signal, and that continuous feedback transforms how teams think and design.',
      },
      // ---- HARD (additional) ----
      {
        id: 'ybyr-h4',
        difficulty: 'hard',
        question: 'Which of the four DORA metrics specifically measures the time from code commit to running in production?',
        choices: [
          'Deployment frequency',
          'Lead time for changes',
          'Change failure rate',
          'Mean Time to Restore (MTTR)',
        ],
        correctIndex: 1,
        explanation: 'Lead time for changes measures the elapsed time between committing code and that code running in production \u2014 a key indicator of delivery efficiency.',
      },
      {
        id: 'ybyr-h5',
        difficulty: 'hard',
        question: 'The deep dive describes "unclear boundaries" as a failure mode. Why does a shared monolith with no ownership lines cause this?',
        choices: [
          'Monoliths are inherently unreliable',
          'No team has a clear boundary, so production problems become "no-one\'s problem" \u2014 everyone is accountable, so no-one is',
          'Monoliths cannot be deployed independently',
          'Shared code always has slower test suites',
        ],
        correctIndex: 1,
        explanation: 'YBYR requires clear service boundaries. Without them, ownership is diffuse \u2014 the on-call question "who\'s responsible?" has no answer, and incidents drag on.',
      },
      {
        id: 'ybyr-h6',
        difficulty: 'hard',
        question: 'According to the deep dive, how is a well-run on-call rotation different from a punishment?',
        choices: [
          'Well-run on-call pays more per alert',
          'It is the signal that drives design improvement \u2014 repeated alerts give the team both the motivation and authority to fix root causes',
          'It involves fewer alerts by design',
          'It runs only during business hours',
        ],
        correctIndex: 1,
        explanation: 'On-call is a feedback mechanism: each page is information about a design flaw the team is uniquely positioned to fix. Handled well, it continuously improves the system.',
      },
      {
        id: 'ybyr-h7',
        difficulty: 'hard',
        question: 'The deep dive lists "feature flags" as a complementary practice. What specific risk do feature flags help manage?',
        choices: [
          'They reduce the total number of features shipped',
          'They allow teams to release code to production while controlling exposure \u2014 reducing blast radius if something goes wrong',
          'They replace automated testing',
          'They prevent the need for rollbacks entirely',
        ],
        correctIndex: 1,
        explanation: 'Feature flags decouple deployment from release \u2014 code goes to production (fast feedback) while only being exposed to a subset of users, limiting risk.',
      },
      {
        id: 'ybyr-h8',
        difficulty: 'hard',
        question: 'The deep dive says YBYR is the "cultural foundation of DevOps." What does "cultural foundation" mean here?',
        choices: [
          'DevOps is a culture created by Werner Vogels',
          'YBYR embodies the values and mindset that DevOps practices are built on \u2014 ownership, feedback, and shared accountability between build and run',
          'YBYR requires a specific DevOps toolchain to work',
          'DevOps culture is defined by DORA metrics alone',
        ],
        correctIndex: 1,
        explanation: 'YBYR is not a practice or tool \u2014 it\'s the cultural shift that makes DevOps practices meaningful. Without the ownership mindset, tools alone don\'t deliver the benefits.',
      },
      {
        id: 'ybyr-h9',
        difficulty: 'hard',
        question: 'The deep dive says YBYR turns a developer into a "systems thinker." What specific capability does this describe?',
        choices: [
          'Thinking only about distributed systems patterns',
          'Understanding that every architectural decision has operational consequences, and designing with both in mind',
          'Learning Kubernetes and observability tools',
          'Managing a team as well as writing code',
        ],
        correctIndex: 1,
        explanation: 'A systems thinker understands the full feedback loop: design choices become operational realities, and operational pain is a signal about design flaws.',
      },
      {
        id: 'ybyr-h10',
        difficulty: 'hard',
        question: 'Progressive deployment (canary / blue-green) is listed as complementary to YBYR. What specific problem does it solve?',
        choices: [
          'It automates documentation updates after deployment',
          'It reduces cloud costs through resource sharing',
          'It allows teams to validate changes in production incrementally before full rollout \u2014 reducing change failure rate',
          'It replaces the need for a staging environment entirely',
        ],
        correctIndex: 2,
        explanation: 'Progressive deployment reduces risk by limiting blast radius: a canary rollout exposes a small percentage of traffic to the new version before full release.',
      },
    ],
  },
};
